# 🌸 Analisis Berita: Skip-gram

Notebook ini merepresentasikan berita menjadi vektor dengan **Skip-gram**, lalu menggunakannya untuk klasifikasi berita **Sport** dan **Finance** dengan **Naive Bayes**.

Alur pengerjaan:

1. Membaca Data dan Pengaturan Penyimpanan Hasil
2. Preprocessing (tanpa stemming)
3. Skip-gram, termasuk kata target dan konteks
4. Eksperimen `vector_size` dan `window` dengan GridSearchCV
5. Evaluasi Skip-gram pada data uji
6. Eksperimen skenario preprocessing (V1 sampai V4)
7. Menyimpan model

## 1. Membaca Data dan Pengaturan Penyimpanan Hasil

### 1.1 Membaca Data

Dataset hasil crawling berita Sport dan Finance dibaca menggunakan `pandas`. Jumlah baris, kolom, dan distribusi label dicek sekali di awal untuk memastikan data sesuai dengan yang ditargetkan.

In [1]:
import pandas as pd

df = pd.read_csv("dataset_berita.csv")

print("Ukuran dataset:", df.shape)
print("\nData kosong per kolom:")
print(df.isnull().sum())
print("\nJumlah data duplikat:", df.duplicated().sum())
print("\nDistribusi label:")
print(df["label"].value_counts())

df.head()

Ukuran dataset: (200, 3)

Data kosong per kolom:
id            0
isi_berita    0
label         0
dtype: int64

Jumlah data duplikat: 0

Distribusi label:
label
sport      100
finance    100
Name: count, dtype: int64

   id                                         isi_berita  label
0   1  Jakarta - Putri Kusuma Wardani percaya diri de...  sport
1   2  Jakarta - Mata Derrick Michael Xzavierro berbi...  sport
2   3  Jakarta - Marc Marquez masih harus beradaptasi...  sport
3   4  Jakarta - Momen debut di Asian Games 2026 tak ...  sport
4   5  Jakarta - MotoGP 2026 akan berlanjut ke San Ma...  sport

### 1.2 Pengaturan Penyimpanan Hasil

Proses yang lama (Skip-gram dan GridSearchCV) hanya perlu dijalankan sekali. Hasilnya disimpan ke dalam folder `FOLDER`. Saat notebook dijalankan ulang, setiap tahap akan **mengecek filenya terlebih dahulu**: jika file ada, hasil langsung dimuat; jika belum ada, tahap tersebut dijalankan lalu hasilnya disimpan.

Pengaturan:

- `FOLDER`: lokasi penyimpanan hasil. Dapat diganti, misalnya `r"C:\Users\acer\Downloads\hasil"`.
- `FORCE_ULANG`: jika diubah menjadi `True`, semua tahap dijalankan ulang dan file lama ditimpa.

Cache juga menyimpan sidik (hash) dari teks hasil preprocessing dan parameter GridSearch. Jika teks atau parameternya berubah, tahap yang bergantung padanya otomatis dihitung ulang sehingga hasil lama yang sudah tidak sesuai tidak ikut terpakai.

File yang dihasilkan:

| File | Isi |
|---|---|
| `hasil_preprocessing.csv` | Teks utama: `teks_skipgram` (V3) |
| `skipgram_demo.joblib` dan `hasil_skipgram.csv` | Skip-gram `vector_size=100` dan tabel 101 kolom |
| `gridsearch_skipgram.joblib` | Hasil GridSearchCV |
| `hasil_preprocessing_skenario.csv` | Teks hasil skenario V1 sampai V4 |
| `hasil_eksperimen_skenario_skipgram.joblib` dan `.csv` | Tabel perbandingan skenario V1 sampai V4 |

File `.joblib` yang berisi kelas `SkipgramVectorizer` hanya dapat dimuat di notebook ini, karena kelasnya didefinisikan di sini. Model untuk aplikasi (`skipgram.model` dan `naive_bayes.joblib`) disimpan terpisah pada bagian 7.

File lama dari versi yang masih memakai TF-IDF (`tfidf.joblib`, `hasil_tfidf.csv`, `gridsearch_tfidf.joblib`, dan `hasil_eksperimen_skenario.*`) sudah tidak dipakai dan boleh dihapus. File lama dari versi yang memakai stemming (`hasil_preprocessing_tanda_baca.csv` dan `hasil_eksperimen_tanda_baca.*`) juga boleh dihapus.

In [2]:
import os
import joblib

FOLDER = "hasil5"        # contoh lain: r"C:\Users\acer\Downloads\hasil"
FORCE_ULANG = False     # True = abaikan file yang sudah ada dan hitung ulang semuanya

os.makedirs(FOLDER, exist_ok=True)


def jalur(nama):
    return os.path.join(FOLDER, nama)


def ada(nama):
    return os.path.exists(jalur(nama)) and not FORCE_ULANG


def muat_cache(nama, **syarat):
    """Mengembalikan isi file jika ada dan semua syarat (sidik, parameter) cocok.
    Jika tidak, mengembalikan None."""
    if not ada(nama):
        return None
    try:
        isi = joblib.load(jalur(nama))
    except Exception:
        return None
    for kunci, nilai in syarat.items():
        if isi.get(kunci) != nilai:
            return None
    return isi


def simpan_cache(nama, **isi):
    joblib.dump(isi, jalur(nama))

## 2. Preprocessing

Preprocessing dilakukan dalam satu fungsi `preprocess_teks` **tanpa stemming**, sehingga kata tetap berbentuk aslinya (misalnya `memenangkan` tidak diubah menjadi `menang`) dan prosesnya hanya memakan waktu beberapa detik.

Teks utama untuk Skip-gram adalah `teks_skipgram`: tanda baca dihapus dan stopword **dipertahankan** (skenario V3). Kalimat dibiarkan utuh agar konteks di sekitar setiap kata tetap lengkap. Skenario lain (V1, V2, dan V4) hanya dipakai pada eksperimen di bagian 6.

Tahapan di dalam fungsi `preprocess_teks`:

1. Mengubah teks menjadi huruf kecil (case folding).
2. Menghapus URL dan angka.
3. Menghapus tanda baca, atau mempertahankannya sebagai token tersendiri (hanya pada eksperimen).
4. Menghapus stopword atau mempertahankannya, sesuai parameter `hapus_stopword`.

Parameter bawaan fungsi adalah `hapus_tanda_baca=True` dan `hapus_stopword=False` (skenario V3). Library `Sastrawi` hanya dipakai untuk daftar stopword Bahasa Indonesia.

Hasilnya disimpan pada kolom `teks_skipgram` serta file `hasil_preprocessing.csv`. Karena prosesnya cepat, preprocessing selalu dijalankan ulang sehingga perubahan pada fungsi langsung terpakai.

In [3]:
%pip install Sastrawi

Requirement already satisfied: Sastrawi in C:\Users\acer\AppData\Roaming\Python\Python312\site-packages (1.0.1)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import re
import hashlib
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

stopword = set(StopWordRemoverFactory().get_stop_words())


def preprocess_teks(teks, hapus_tanda_baca=True, hapus_stopword=False):
    """Preprocessing tanpa stemming.
    Nilai bawaan (tanda baca dihapus, stopword dipertahankan) = skenario V3,
    dipakai untuk teks Skip-gram."""
    teks = teks.lower()                           # case folding
    teks = re.sub(r"http\S+|www\S+", " ", teks)   # hapus URL
    teks = re.sub(r"\d+", " ", teks)              # hapus angka

    if hapus_tanda_baca:
        teks = re.sub(r"[^\w\s]|_", " ", teks)           # buang tanda baca
    else:
        teks = re.sub(r"([^\w\s]|_)", r" \1 ", teks)     # tanda baca menjadi token tersendiri

    tokens = teks.split()
    if hapus_stopword:
        tokens = [k for k in tokens if k not in stopword]   # hapus stopword
    return " ".join(tokens)


# Teks utama untuk Skip-gram
df["teks_skipgram"] = df["isi_berita"].apply(preprocess_teks)   # V3

df[["id", "label", "teks_skipgram"]].to_csv(
    jalur("hasil_preprocessing.csv"), index=False, encoding="utf-8-sig"
)
print("Hasil preprocessing disimpan:", jalur("hasil_preprocessing.csv"))

# Sidik teks: dipakai untuk memastikan cache tahap berikutnya masih sesuai
SIDIK_SKIPGRAM = hashlib.md5("||".join(df["teks_skipgram"]).encode("utf-8")).hexdigest()

print("Jumlah stopword            :", len(stopword))
print("Total token teks Skip-gram :", sum(len(t.split()) for t in df["teks_skipgram"]))
df[["isi_berita", "teks_skipgram"]].head()

Hasil preprocessing disimpan: hasil5\hasil_preprocessing.csv
Jumlah stopword            : 123
Total token teks Skip-gram : 67583

,isi_berita,teks_skipgram
0,Jakarta - Putri Kusuma Wardani percaya diri de...,jakarta putri kusuma wardani percaya diri deng...
1,Jakarta - Mata Derrick Michael Xzavierro berbi...,jakarta mata derrick michael xzavierro berbina...
2,Jakarta - Marc Marquez masih harus beradaptasi...,jakarta marc marquez masih harus beradaptasi d...
3,Jakarta - Momen debut di Asian Games 2026 tak ...,jakarta momen debut di asian games tak mau dis...
4,Jakarta - MotoGP 2026 akan berlanjut ke San Ma...,jakarta motogp akan berlanjut ke san marino se...

## 3. Skip-gram

### 3.1 Menyiapkan Kelas Skip-gram

Skip-gram merupakan salah satu arsitektur Word2Vec. Setiap kata diubah menjadi vektor dengan jumlah dimensi sebesar `vector_size`. Satu berita kemudian direpresentasikan sebagai **rata-rata vektor kata-kata** di dalamnya. Dengan cara ini, jumlah kolom ditentukan oleh `vector_size`, bukan oleh jumlah kata unik pada seluruh berita.

Kelas `SkipgramVectorizer` membungkus Word2Vec agar dapat dipakai bersama `Pipeline` dan `GridSearchCV`. Skip-gram dilatih ulang di dalam setiap fold sehingga data uji tidak ikut dipelajari.

In [5]:
%pip install gensim

Requirement already satisfied: gensim in C:\Users\acer\AppData\Roaming\Python\Python312\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in C:\Users\acer\AppData\Roaming\Python\Python312\site-packages (from gensim) (2.3.0)
Requirement already satisfied: scipy>=1.7.0 in C:\Users\acer\AppData\Roaming\Python\Python312\site-packages (from gensim) (1.15.3)
Requirement already satisfied: smart_open>=1.8.1 in C:\Users\acer\AppData\Roaming\Python\Python312\site-packages (from gensim) (8.0.2)
Requirement already satisfied: wrapt in C:\Users\acer\AppData\Roaming\Python\Python312\site-packages (from smart_open>=1.8.1->gensim) (2.5.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import numpy as np
from gensim.models import Word2Vec
from sklearn.base import BaseEstimator, TransformerMixin


class SkipgramVectorizer(BaseEstimator, TransformerMixin):
    """Teks -> vektor dokumen (rata-rata vektor kata hasil Skip-gram)."""

    def __init__(self, vector_size=100, window=5, min_count=1, epochs=50, seed=42):
        self.vector_size = vector_size
        self.window = window
        self.min_count = min_count
        self.epochs = epochs
        self.seed = seed

    def fit(self, X, y=None):
        corpus = [t.split() for t in X]
        self.w2v_ = Word2Vec(
            sentences=corpus,
            vector_size=self.vector_size,
            window=self.window,
            min_count=self.min_count,
            sg=1,                  # sg=1 berarti Skip-gram
            epochs=self.epochs,
            seed=self.seed,
            workers=1,             # agar hasil dapat diulang (reproducible)
        )
        return self

    def transform(self, X):
        hasil = []
        for t in X:
            vec = [self.w2v_.wv[k] for k in t.split() if k in self.w2v_.wv]
            hasil.append(np.mean(vec, axis=0) if vec else np.zeros(self.vector_size))
        return np.array(hasil)

In [7]:
import pandas as pd
import numpy as np
from IPython.display import display

# 1. Latih Skip-gram dan ubah semua berita menjadi vektor
sg = SkipgramVectorizer(vector_size=100, window=5).fit(df["teks_skipgram"])
X_sg = sg.transform(df["teks_skipgram"])

# 2. Ukuran hasil
print("Jumlah kata unik (kosakata Skip-gram):", len(sg.w2v_.wv))
print("Ukuran matriks Skip-gram              :", X_sg.shape)
print("Jumlah kolom + label                  :", X_sg.shape[1] + 1)

# 3. Tabel hasil: 100 kolom vektor + label = 101 kolom
df_sg = pd.DataFrame(X_sg, columns=[f"v{i}" for i in range(1, X_sg.shape[1] + 1)])
df_sg["label"] = df["label"].values

print("\nTabel Skip-gram (5 berita pertama, 10 kolom pertama + label):")
display(df_sg.iloc[:5, list(range(10)) + [-1]])

# 4. Vektor satu kata (ganti 'motogp' dengan kata lain yang ada di datamu)
kata = "motogp"
print(f"\nVektor kata '{kata}' (10 dimensi pertama dari {sg.vector_size}):")
print(sg.w2v_.wv[kata][:10])

# 5. Kata-kata yang paling mirip
print(f"\n5 kata paling mirip dengan '{kata}':")
for k, skor in sg.w2v_.wv.most_similar(kata, topn=5):
    print(f"  {k:<15} {skor:.4f}")

# 6. Rata-rata vektor per label (untuk melihat sport dan finance berbeda atau tidak)
print("\nRata-rata 5 dimensi pertama per label:")
display(df_sg.groupby("label")[["v1", "v2", "v3", "v4", "v5"]].mean().round(4))

Jumlah kata unik (kosakata Skip-gram): 7568
Ukuran matriks Skip-gram              : (200, 100)
Jumlah kolom + label                  : 101

Tabel Skip-gram (5 berita pertama, 10 kolom pertama + label):

,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,label
0,0.507398,0.034776,-0.293952,0.089171,0.097252,0.544435,-0.212268,0.041457,-0.288005,0.128534,sport
1,0.455892,-0.044848,-0.305015,0.026712,0.075877,0.636112,-0.114919,0.183454,-0.305837,-0.062704,sport
2,0.555008,-0.154921,-0.355984,-0.061660,0.035152,0.616313,-0.061790,0.239603,-0.060613,-0.124050,sport
3,0.454859,-0.034748,-0.354117,-0.006549,0.075459,0.564348,-0.222063,0.087649,-0.230089,0.050164,sport
4,0.565319,0.049084,-0.442544,0.096601,0.152404,0.658893,-0.026523,0.080589,-0.167623,-0.021505,sport

Vektor kata 'motogp' (10 dimensi pertama dari 100):
[ 1.0122964   0.21532795 -0.6862337   0.39061114  0.39328647  0.31087306
  0.14286491 -0.5204704  -0.02626511 -0.10659632]

5 kata paling mirip dengan 'motogp':
  san             0.7329
  merupaya        0.7068
  dominasi        0.7059
  ngebut          0.7052
  home            0.7019

Rata-rata 5 dimensi pertama per label:

             v1      v2      v3      v4      v5
label
finance  0.2877 -0.1735 -0.1907  0.1348 -0.0557
sport    0.3830 -0.0124 -0.3416  0.1205  0.0369

### 3.2 Kata Target dan Konteks

Skip-gram belajar dengan cara **menebak kata-kata di sekitar sebuah kata**. Kata yang sedang diperhatikan disebut **kata target**, dan kata-kata di sekelilingnya yang masuk dalam jendela (`window`) disebut **konteks**. Untuk `window = w`, konteks sebuah kata target adalah `w` kata di sebelah kirinya dan `w` kata di sebelah kanannya.

Contoh pada kalimat `harga emas naik rupiah menguat` dengan `window = 2`:

| Kata target | Konteks |
|---|---|
| harga | emas, naik |
| emas | harga, naik, rupiah |
| naik | harga, emas, rupiah, menguat |
| rupiah | emas, naik, menguat |
| menguat | naik, rupiah |

Setiap kata target dipasangkan dengan setiap kata konteksnya menjadi pasangan `(target, konteks)`, misalnya `(emas, harga)`, `(emas, naik)`, dan `(emas, rupiah)`. Pasangan inilah yang dipakai untuk melatih Skip-gram. Pada `gensim`, lebar jendela di setiap kata target secara bawaan diacak antara 1 sampai `window`, sehingga kata yang lebih dekat lebih sering dipakai sebagai konteks.

Kode berikut menampilkan kata target dan konteksnya pada berita pertama di dataset.

In [8]:
def konteks_kata(tokens, i, window):
    """Konteks kiri dan kanan dari kata pada posisi i."""
    kiri = tokens[max(0, i - window):i]
    kanan = tokens[i + 1:i + 1 + window]
    return kiri, kanan


def tabel_target_konteks(tokens, window):
    baris = []
    for i, target in enumerate(tokens):
        kiri, kanan = konteks_kata(tokens, i, window)
        baris.append({
            "posisi": i,
            "kata_target": target,
            "konteks_kiri": ", ".join(kiri),
            "konteks_kanan": ", ".join(kanan),
        })
    return pd.DataFrame(baris)


# Contoh: 12 kata pertama dari berita pertama, window = 2
WINDOW_CONTOH = 2
tokens_contoh = df["teks_skipgram"].iloc[0].split()[:12]

print("Kalimat contoh:", " ".join(tokens_contoh))
print(f"\nKata target dan konteksnya (window = {WINDOW_CONTOH}):")
display(tabel_target_konteks(tokens_contoh, WINDOW_CONTOH))

# Pasangan (target, konteks) yang dipakai untuk melatih Skip-gram
pasangan = []
for i, target in enumerate(tokens_contoh):
    kiri, kanan = konteks_kata(tokens_contoh, i, WINDOW_CONTOH)
    pasangan += [(target, k) for k in kiri + kanan]

df_pasangan = pd.DataFrame(pasangan, columns=["kata_target", "kata_konteks"])
print(f"\nJumlah pasangan (target, konteks) dari 12 kata ini: {len(df_pasangan)}")
display(df_pasangan.head(15))

Kalimat contoh: jakarta putri kusuma wardani percaya diri dengan komposisi beregu putri yang dipilih

Kata target dan konteksnya (window = 2):

    posisi kata_target       konteks_kiri      konteks_kanan
0        0     jakarta                         putri, kusuma
1        1       putri            jakarta    kusuma, wardani
2        2      kusuma     jakarta, putri   wardani, percaya
3        3     wardani      putri, kusuma      percaya, diri
4        4     percaya    kusuma, wardani       diri, dengan
5        5        diri   wardani, percaya  dengan, komposisi
6        6      dengan      percaya, diri  komposisi, beregu
7        7   komposisi       diri, dengan      beregu, putri
8        8      beregu  dengan, komposisi        putri, yang
9        9       putri  komposisi, beregu      yang, dipilih
10      10        yang      beregu, putri            dipilih
11      11     dipilih        putri, yang

Jumlah pasangan (target, konteks) dari 12 kata ini: 42

   kata_target kata_konteks
0      jakarta        putri
1      jakarta       kusuma
2        putri      jakarta
3        putri       kusuma
4        putri      wardani
5       kusuma      jakarta
6       kusuma        putri
7       kusuma      wardani
8       kusuma      percaya
9      wardani        putri
10     wardani       kusuma
11     wardani      percaya
12     wardani         diri
13     percaya       kusuma
14     percaya      wardani

In [9]:
# ---------- Pengaruh ukuran window pada satu kata target ----------
tokens_doc = df["teks_skipgram"].iloc[0].split()
posisi = min(15, len(tokens_doc) - 1)

print("Kata target:", tokens_doc[posisi], "\n")
for w in [1, 2, 3, 5, 10]:
    kiri, kanan = konteks_kata(tokens_doc, posisi, w)
    print(f"window={w:<2} | kiri: {kiri} | kanan: {kanan}")

# ---------- Pengaruh window pada jumlah pasangan (target, konteks) ----------
def hitung_pasangan(n, w):
    return sum(min(i, w) + min(n - 1 - i, w) for i in range(n))


jumlah_token = [len(t.split()) for t in df["teks_skipgram"]]

print("\nJumlah pasangan (target, konteks) pada seluruh berita:")
display(pd.DataFrame({
    "window": [2, 5, 10],
    "jumlah pasangan": [sum(hitung_pasangan(n, w) for n in jumlah_token) for w in [2, 5, 10]],
}))

Kata target: games

window=1  | kiri: ['asian'] | kanan: ['dia']
window=2  | kiri: ['untuk', 'asian'] | kanan: ['dia', 'juga']
window=3  | kiri: ['pbsi', 'untuk', 'asian'] | kanan: ['dia', 'juga', 'menyebut']
window=5  | kiri: ['yang', 'dipilih', 'pbsi', 'untuk', 'asian'] | kanan: ['dia', 'juga', 'menyebut', 'chemistry', 'satu']
window=10 | kiri: ['diri', 'dengan', 'komposisi', 'beregu', 'putri', 'yang', 'dipilih', 'pbsi', 'untuk', 'asian'] | kanan: ['dia', 'juga', 'menyebut', 'chemistry', 'satu', 'sama', 'lain', 'sudah', 'klop', 'bulutangkis']

Jumlah pasangan (target, konteks) pada seluruh berita:

   window  jumlah pasangan
0       2           269132
1       5           669830
2      10          1329660

Kata target yang sama muncul berkali-kali di banyak berita, dan konteksnya berbeda-beda di setiap kemunculan. Skip-gram merangkum semua konteks itu ke dalam satu vektor untuk setiap kata, sehingga kata yang konteksnya mirip akan memiliki vektor yang berdekatan. Kode berikut menghitung kata-kata yang paling sering menjadi konteks dari sebuah kata target pada seluruh berita (`window = 5`).

In [10]:
from collections import Counter


def konteks_terbanyak(kata, window=5, top=8):
    hitung = Counter()
    jumlah_muncul = 0
    for teks in df["teks_skipgram"]:
        tokens = teks.split()
        for i, w in enumerate(tokens):
            if w == kata:
                jumlah_muncul += 1
                kiri, kanan = konteks_kata(tokens, i, window)
                hitung.update(kiri + kanan)
    return jumlah_muncul, hitung.most_common(top)


for kata in ["motogp", "rupiah"]:
    jumlah_muncul, teratas = konteks_terbanyak(kata)
    if jumlah_muncul == 0:
        print(f"'{kata}' tidak ada di data, ganti dengan kata lain.\n")
        continue

    print(f"Kata target '{kata}' (muncul {jumlah_muncul} kali) -> konteks yang paling sering:")
    for k, n in teratas:
        print(f"  {k:<15} {n}")
    print()

Kata target 'motogp' (muncul 99 kali) -> konteks yang paling sering:
  motogp          50
  marino          20
  klasemen        20
  san             19
  marc            18
  di              18
  balapan         17
  marquez         16

Kata target 'rupiah' (muncul 13 kali) -> konteks yang paling sering:
  juta            4
  dan             4
  orang           4
  as              4
  omzet           3
  yang            3
  ratusan         3
  terhadap        3

### 3.3 Melatih Skip-gram dan Menghitung Jumlah Kata Unik

Skip-gram dilatih pada teks Skip-gram (stopword dipertahankan) dengan `vector_size=100` dan `window=5` sebagai pengaturan awal. Jumlah kata unik pada teks input (sebelum Skip-gram) dibandingkan dengan jumlah kata pada kosakata Skip-gram.

Dengan `min_count=1`, kedua jumlah itu sama karena setiap kata yang muncul minimal sekali ikut dipelajari. Jika `min_count` diperbesar, kata yang jarang muncul akan terbuang dan jumlah kosakata menurun.

In [11]:
jumlah_kata_sebelum = len(set(w for t in df["teks_skipgram"] for w in t.split()))

corpus = [teks.split() for teks in df["teks_skipgram"]]

w2v = Word2Vec(
    sentences=corpus,
    vector_size=100,
    window=5,
    min_count=1,
    sg=1,
    epochs=50,
    seed=42,
    workers=1
)

jumlah_kata_sesudah = len(w2v.wv)

print("Kata unik sebelum Skip-gram :", jumlah_kata_sebelum)
print("Kata unik sesudah Skip-gram :", jumlah_kata_sesudah)

Kata unik sebelum Skip-gram : 7568
Kata unik sesudah Skip-gram : 7568

### 3.4 Ukuran Matriks Skip-gram

Pada Skip-gram, jumlah kolom hanya sebanyak `vector_size`, bukan sebanyak kata unik. Setelah label ditambahkan sebagai satu kolom, tabel Skip-gram dengan `vector_size=100` memiliki 101 kolom. Hasilnya disimpan pada `skipgram_demo.joblib`.

In [12]:
cache = muat_cache("skipgram_demo.joblib", sidik=SIDIK_SKIPGRAM)

if cache:
    sg_vec = cache["sg_vec"]
    X_sg = cache["X_sg"]
    print("Hasil Skip-gram dimuat dari file.")
else:
    print("File belum ada, Skip-gram dilatih...")
    sg_vec = SkipgramVectorizer(vector_size=100, window=5).fit(df["teks_skipgram"])
    X_sg = sg_vec.transform(df["teks_skipgram"])
    simpan_cache("skipgram_demo.joblib", sidik=SIDIK_SKIPGRAM, sg_vec=sg_vec, X_sg=X_sg)
    print("Hasil Skip-gram disimpan.")

ringkasan = pd.DataFrame({
    "Kata unik (kosakata)": [len(sg_vec.w2v_.wv)],
    "Jumlah kolom fitur": [X_sg.shape[1]],
    "Kolom + label": [X_sg.shape[1] + 1],
    "Ukuran matriks": [str(X_sg.shape)],
})

display(ringkasan)

File belum ada, Skip-gram dilatih...
Hasil Skip-gram disimpan.

   Kata unik (kosakata)  Jumlah kolom fitur  Kolom + label Ukuran matriks
0                  7568                 100            101     (200, 100)

### 3.5 Contoh Vektor Skip-gram

Pada Skip-gram, satu kata berupa vektor padat dengan jumlah dimensi sebesar `vector_size`. Kata yang konteksnya mirip memiliki vektor yang berdekatan, sehingga dapat dilihat dari daftar kata yang paling mirip.

In [13]:
# ---------- Skip-gram: vektor satu kata ----------
print("Vektor kata 'motogp' (10 dimensi pertama dari", sg_vec.vector_size, "dimensi):")
print(sg_vec.w2v_.wv["motogp"][:10])

print("\n5 kata paling mirip dengan 'motogp':")
for kata, skor in sg_vec.w2v_.wv.most_similar("motogp", topn=5):
    print(f"  {kata:<15} {skor:.4f}")

Vektor kata 'motogp' (10 dimensi pertama dari 100 dimensi):
[ 1.0122964   0.21532795 -0.6862337   0.39061114  0.39328647  0.31087306
  0.14286491 -0.5204704  -0.02626511 -0.10659632]

5 kata paling mirip dengan 'motogp':
  san             0.7329
  merupaya        0.7068
  dominasi        0.7059
  ngebut          0.7052
  home            0.7019

In [14]:
# ---------- Skip-gram: tabel seluruh berita (100 kolom + label = 101 kolom) ----------
df_sg = pd.DataFrame(
    X_sg,
    columns=[f"v{i}" for i in range(1, X_sg.shape[1] + 1)]
)
df_sg["label"] = df["label"].values

print("Ukuran tabel Skip-gram:", df_sg.shape)
display(df_sg.head(5))

df_sg.to_csv(jalur("hasil_skipgram.csv"), index=False, encoding="utf-8-sig")
print("Hasil Skip-gram berhasil disimpan:", jalur("hasil_skipgram.csv"))

Ukuran tabel Skip-gram: (200, 101)

,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,...,v92,v93,v94,v95,v96,v97,v98,v99,v100,label
0,0.507398,0.034776,-0.293952,0.089171,0.097252,0.544435,-0.212268,0.041457,-0.288005,0.128534,...,-0.047258,-0.002179,-0.082693,-0.089639,-0.224379,0.312498,0.322728,-0.155806,-0.059678,sport
1,0.455892,-0.044848,-0.305015,0.026712,0.075877,0.636112,-0.114919,0.183454,-0.305837,-0.062704,...,-0.131669,-0.121047,-0.152694,-0.174509,-0.166385,0.096833,0.323342,-0.174427,-0.097869,sport
2,0.555008,-0.154921,-0.355984,-0.061660,0.035152,0.616313,-0.061790,0.239603,-0.060613,-0.124050,...,-0.142034,-0.033722,-0.151732,-0.229143,-0.086386,-0.073147,0.248612,-0.252365,-0.048655,sport
3,0.454859,-0.034748,-0.354117,-0.006549,0.075459,0.564348,-0.222063,0.087649,-0.230089,0.050164,...,-0.138772,0.011697,-0.102712,-0.091588,-0.173568,0.283644,0.332725,-0.164999,-0.061546,sport
4,0.565319,0.049084,-0.442544,0.096601,0.152404,0.658893,-0.026523,0.080589,-0.167623,-0.021505,...,-0.206222,-0.110830,-0.061468,-0.312537,-0.114260,-0.035543,0.320504,-0.371817,-0.020651,sport

Hasil Skip-gram berhasil disimpan: hasil5\hasil_skipgram.csv

## 4. Eksperimen `vector_size` dan `window` dengan GridSearchCV

### 4.1 Membagi Data Latih dan Data Uji

Data dibagi menjadi 80% data latih dan 20% data uji dengan `stratify` agar proporsi sport dan finance tetap seimbang. GridSearchCV hanya memakai data latih. Data uji baru dipakai pada tahap evaluasi akhir.

Karena jumlah data hanya 200 berita, data uji berisi 40 berita. Selisih satu berita saja sudah mengubah akurasi sebesar 2,5%, sehingga akurasi cross validation (CV) lebih layak dijadikan patokan utama.

`X_train` dan `X_test` berisi teks Skip-gram.

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.naive_bayes import GaussianNB

X = df["teks_skipgram"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print("Data latih:", len(X_train))
print("Data uji  :", len(X_test))

Data latih: 160
Data uji  : 40

### 4.2 GridSearchCV untuk Skip-gram + Naive Bayes

Kombinasi yang dicoba:

- `vector_size`: 50, 100, 200, 300
- `window`: 3, 5, 10

Naive Bayes yang dipakai untuk Skip-gram adalah `GaussianNB`, karena vektor Skip-gram memiliki nilai negatif sedangkan `MultinomialNB` hanya menerima nilai non-negatif. Seluruh kombinasi diuji dengan 5-fold cross validation sehingga ada 12 kombinasi × 5 fold = 60 kali pelatihan. Hasilnya disimpan pada `gridsearch_skipgram.joblib`; jika parameter di bawah diubah, GridSearch otomatis dijalankan ulang.

In [16]:
pipe_sg = Pipeline([
    ("sg", SkipgramVectorizer()),
    ("nb", GaussianNB()),
])

param_sg = {
    "sg__vector_size": [50, 100, 200, 300],
    "sg__window": [3, 5, 10],
}

cache = muat_cache("gridsearch_skipgram.joblib", sidik=SIDIK_SKIPGRAM, param=param_sg)

if cache:
    gs_sg = cache["gs"]
    print("Hasil GridSearchCV Skip-gram dimuat dari file.")
else:
    print("File belum ada, GridSearchCV Skip-gram dijalankan...")
    gs_sg = GridSearchCV(pipe_sg, param_sg, cv=cv, scoring="accuracy")
    gs_sg.fit(X_train, y_train)
    simpan_cache("gridsearch_skipgram.joblib", sidik=SIDIK_SKIPGRAM, param=param_sg, gs=gs_sg)
    print("Hasil GridSearchCV Skip-gram disimpan.")

print("Parameter terbaik Skip-gram :", gs_sg.best_params_)
print("Akurasi CV terbaik          :", round(gs_sg.best_score_, 4))

File belum ada, GridSearchCV Skip-gram dijalankan...
Hasil GridSearchCV Skip-gram disimpan.
Parameter terbaik Skip-gram : {'sg__vector_size': 100, 'sg__window': 10}
Akurasi CV terbaik          : 0.9812

In [17]:
hasil = pd.DataFrame(gs_sg.cv_results_)

display(
    hasil[
        [
            "param_sg__vector_size",
            "param_sg__window",
            "mean_test_score"
        ]
    ].sort_values("mean_test_score", ascending=False)
)

    param_sg__vector_size  param_sg__window  mean_test_score
11                    300                10          0.98125
5                     100                10          0.98125
0                      50                 3          0.97500
1                      50                 5          0.97500
3                     100                 3          0.97500
2                      50                10          0.97500
6                     200                 3          0.97500
4                     100                 5          0.97500
7                     200                 5          0.97500
8                     200                10          0.97500
9                     300                 3          0.97500
10                    300                 5          0.97500

### 4.3 Tabel Eksperimen `vector_size` dan `window`

Tabel berikut menampilkan rata-rata akurasi cross validation untuk setiap kombinasi. Baris menunjukkan `vector_size` dan kolom menunjukkan `window`. Kombinasi dengan nilai tertinggi menjadi parameter terbaik.

In [18]:
hasil_sg = pd.DataFrame(gs_sg.cv_results_)

tabel_eksperimen = hasil_sg.pivot(
    index="param_sg__vector_size",
    columns="param_sg__window",
    values="mean_test_score"
).round(4)

tabel_eksperimen.index.name = "vector_size"
tabel_eksperimen.columns.name = "window"

display(tabel_eksperimen)

window          3      5       10
vector_size
50           0.975  0.975  0.9750
100          0.975  0.975  0.9812
200          0.975  0.975  0.9750
300          0.975  0.975  0.9812

## 5. Evaluasi Skip-gram pada Data Uji

Model Skip-gram + Naive Bayes dengan parameter terbaik dari GridSearchCV diuji pada 40 berita uji yang belum pernah dilihat. Hasilnya dilaporkan dengan akurasi CV, akurasi data uji, serta `classification_report` (precision, recall, dan f1-score).

In [19]:
from sklearn.metrics import accuracy_score, classification_report

pred = gs_sg.predict(X_test)

print("===== Skip-gram + Naive Bayes =====")
print(classification_report(y_test, pred))

display(pd.DataFrame([{
    "Model": "Skip-gram + Naive Bayes",
    "Parameter terbaik": gs_sg.best_params_,
    "Akurasi CV (data latih)": round(gs_sg.best_score_, 4),
    "Akurasi data uji": round(accuracy_score(y_test, pred), 4),
}]))

===== Skip-gram + Naive Bayes =====
              precision    recall  f1-score   support

     finance       1.00      1.00      1.00        20
       sport       1.00      1.00      1.00        20

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

,Model,Parameter terbaik,Akurasi CV (data latih),Akurasi data uji
0,Skip-gram + Naive Bayes,"{'sg__vector_size': 100, 'sg__window': 10}",0.9812,1.0

## 6. Eksperimen Skenario Preprocessing (V1 sampai V4)

Bagian ini membandingkan empat skenario preprocessing yang berbeda pada dua hal, yaitu perlakuan **tanda baca** dan perlakuan **stopword**:

| Skenario | Tanda baca | Stopword | Keterangan |
|---|---|---|---|
| V1 | dihapus | dihapus | Menghapus tanda baca dan stopword |
| V2 | dipertahankan | dihapus | Mempertahankan tanda baca, menghapus stopword |
| V3 | dihapus | dipertahankan | Menghapus tanda baca, mempertahankan stopword (**preprocessing utama Skip-gram**) |
| V4 | dipertahankan | dipertahankan | Menjaga semua komponen teks tanpa pembersihan tambahan |

Agar perbandingannya adil, hal-hal berikut dibuat sama pada keempat skenario:

- Semua teks diubah menjadi huruf kecil, serta URL dan angka dihapus. Pada V4, "tanpa pembersihan tambahan" berarti hanya pembersihan dasar ini yang dilakukan, sehingga yang berbeda antar skenario hanya tanda baca dan stopword.
- Tanda baca yang dipertahankan dipisahkan dari kata dan diperlakukan sebagai token tersendiri (misalnya `,` `.` `-`).
- Pembagian data latih dan uji sama dengan bagian 4, dan fold cross validation (`cv`) sama untuk semua skenario.
- Stemming tidak dipakai pada semua skenario.

Setiap skenario diuji dengan Skip-gram + `GaussianNB`, lengkap dengan GridSearchCV.

### 6.1 Membuat Teks untuk Setiap Skenario

Fungsi `preprocess_teks` dari bagian 2 dipanggil dengan pengaturan yang berbeda untuk tiap skenario. Hasilnya disimpan pada kolom `teks_V1` sampai `teks_V4` dan pada file `hasil_preprocessing_skenario.csv`.

In [20]:
PENGATURAN = {
    "V1": {"hapus_tanda_baca": True,  "hapus_stopword": True},
    "V2": {"hapus_tanda_baca": False, "hapus_stopword": True},
    "V3": {"hapus_tanda_baca": True,  "hapus_stopword": False},
    "V4": {"hapus_tanda_baca": False, "hapus_stopword": False},
}

KETERANGAN = {
    "V1": "Hapus tanda baca, hapus stopword",
    "V2": "Pertahankan tanda baca, hapus stopword",
    "V3": "Hapus tanda baca, pertahankan stopword",
    "V4": "Pertahankan semua (tanpa pembersihan tambahan)",
}

for kode, opsi in PENGATURAN.items():
    df[f"teks_{kode}"] = df["isi_berita"].apply(lambda t: preprocess_teks(t, **opsi))

# V3 harus sama dengan teks utama pada bagian 2
assert (df["teks_V3"] == df["teks_skipgram"]).all()

kolom_skenario = [f"teks_{k}" for k in PENGATURAN]
df[["id", "label"] + kolom_skenario].to_csv(
    jalur("hasil_preprocessing_skenario.csv"), index=False, encoding="utf-8-sig"
)
print("Disimpan:", jalur("hasil_preprocessing_skenario.csv"))

# Ringkasan ukuran tiap skenario
ringkasan_skenario = pd.DataFrame([{
    "Skenario": k,
    "Keterangan": KETERANGAN[k],
    "Total token": sum(len(t.split()) for t in df[f"teks_{k}"]),
    "Token unik": len(set(w for t in df[f"teks_{k}"] for w in t.split())),
} for k in PENGATURAN])
display(ringkasan_skenario)

# Contoh: potongan berita pertama pada tiap skenario
contoh = df["isi_berita"].iloc[0][:200]
print("Teks asli (200 karakter pertama):")
print(contoh, "\n")
for k, opsi in PENGATURAN.items():
    print(f"{k}: {preprocess_teks(contoh, **opsi)}\n")

Disimpan: hasil5\hasil_preprocessing_skenario.csv

,Skenario,Keterangan,Total token,Token unik
0,V1,"Hapus tanda baca, hapus stopword",52007,7459
1,V2,"Pertahankan tanda baca, hapus stopword",66936,7498
2,V3,"Hapus tanda baca, pertahankan stopword",67583,7568
3,V4,Pertahankan semua (tanpa pembersihan tambahan),82512,7607

Teks asli (200 karakter pertama):
Jakarta - Putri Kusuma Wardani percaya diri dengan komposisi beregu putri yang dipilih PBSI untuk Asian Games 2026. Dia juga menyebut chemistry satu sama lain sudah klop. Bulutangkis Indonesia mengiri

V1: jakarta putri kusuma wardani percaya diri komposisi beregu putri dipilih pbsi asian games menyebut chemistry satu sama klop bulutangkis indonesia mengiri

V2: jakarta - putri kusuma wardani percaya diri komposisi beregu putri dipilih pbsi asian games . menyebut chemistry satu sama klop . bulutangkis indonesia mengiri

V3: jakarta putri kusuma wardani percaya diri dengan komposisi beregu putri yang dipilih pbsi untuk asian games dia juga menyebut chemistry satu sama lain sudah klop bulutangkis indonesia mengiri

V4: jakarta - putri kusuma wardani percaya diri dengan komposisi beregu putri yang dipilih pbsi untuk asian games . dia juga menyebut chemistry satu sama lain sudah klop . bulutangkis indonesia mengiri

### 6.2 Kata Target dan Konteks pada Setiap Skenario

Skenario yang berbeda menghasilkan deretan token yang berbeda, sehingga konteks yang dilihat Skip-gram juga berbeda:

- Pada **V2 dan V4**, tanda baca ikut menjadi token sehingga bisa muncul sebagai konteks.
- Pada **V3 dan V4**, stopword (misalnya `yang`, `di`, `dengan`) ikut mengisi jendela sehingga kata penting di sekitarnya terdorong lebih jauh dari kata target.

Kode berikut memilih satu kata target dari berita pertama (kata pertama yang konteksnya berbeda di keempat skenario) lalu menampilkan konteks kirinya dan konteks kanannya dengan `window = 3`.

In [21]:
WINDOW_BANDING = 3


def konteks_di_skenario(kode, kata):
    tokens = df[f"teks_{kode}"].iloc[0].split()
    kiri, kanan = konteks_kata(tokens, tokens.index(kata), WINDOW_BANDING)
    return " ".join(kiri), " ".join(kanan)


# Pilih kata pertama di berita pertama yang konteksnya berbeda di keempat skenario.
# Ganti dengan kata lain jika ingin, asalkan kata tersebut ada di berita pertama.
tokens_v1 = df["teks_V1"].iloc[0].split()
kata_target = next(
    (t for t in tokens_v1 if len({konteks_di_skenario(k, t) for k in PENGATURAN}) == len(PENGATURAN)),
    tokens_v1[5]
)

print(f"Kata target: '{kata_target}' pada berita pertama, window = {WINDOW_BANDING}\n")

baris = []
for k in PENGATURAN:
    tokens = df[f"teks_{k}"].iloc[0].split()
    i = tokens.index(kata_target)
    kiri, kanan = konteks_kata(tokens, i, WINDOW_BANDING)
    baris.append({
        "Skenario": k,
        "Konteks kiri": " ".join(kiri),
        "Kata target": kata_target,
        "Konteks kanan": " ".join(kanan),
    })

display(pd.DataFrame(baris))

Kata target: 'wardani' pada berita pertama, window = 3

  Skenario          Konteks kiri Kata target           Konteks kanan
0       V1  jakarta putri kusuma     wardani  percaya diri komposisi
1       V2        - putri kusuma     wardani  percaya diri komposisi
2       V3  jakarta putri kusuma     wardani     percaya diri dengan
3       V4        - putri kusuma     wardani     percaya diri dengan

### 6.3 Menjalankan Eksperimen

Pembagian data dan fold cross validation dibuat satu kali dan dipakai bersama oleh keempat skenario, sehingga yang berubah hanya perlakuan tanda baca dan stopword. Setiap skenario diuji dengan Skip-gram (`GaussianNB`), lengkap dengan GridSearchCV. Karena ada 4 skenario, proses ini adalah bagian yang paling lama. Tabel hasilnya disimpan pada `hasil_eksperimen_skenario_skipgram.joblib` dan `.csv`, sehingga pada proses berikutnya langsung dimuat dari file.

In [22]:
# Pembagian data yang sama dengan bagian 4
idx_train, idx_test = X_train.index, X_test.index
y_tr = df.loc[idx_train, "label"]
y_te = df.loc[idx_test, "label"]


def jalankan_eksperimen():
    baris = []

    for kode in PENGATURAN:
        kolom = f"teks_{kode}"
        X_tr = df.loc[idx_train, kolom]
        X_te = df.loc[idx_test, kolom]

        # jumlah token unik pada skenario ini
        n_vocab = len(set(w for t in df[kolom] for w in t.split()))

        # ---------- Skip-gram + GaussianNB ----------
        gs_s = GridSearchCV(
            Pipeline([
                ("sg", SkipgramVectorizer()),
                ("nb", GaussianNB()),
            ]),
            param_sg,
            cv=cv,
            scoring="accuracy"
        ).fit(X_tr, y_tr)

        baris.append({
            "Skenario": kode,
            "Keterangan": KETERANGAN[kode],
            "Token unik": n_vocab,
            "Jumlah kolom": gs_s.best_params_["sg__vector_size"],
            "Parameter terbaik": gs_s.best_params_,
            "Akurasi CV": round(gs_s.best_score_, 4),
            "Akurasi data uji": round(accuracy_score(y_te, gs_s.predict(X_te)), 4),
        })

        print(f"Skenario {kode} selesai.")

    return pd.DataFrame(baris)


# Sidik seluruh teks skenario, agar cache otomatis dihitung ulang jika teks berubah
SIDIK_SKENARIO = hashlib.md5(
    "||".join("||".join(df[k]) for k in kolom_skenario).encode("utf-8")
).hexdigest()

cache = muat_cache(
    "hasil_eksperimen_skenario_skipgram.joblib",
    sidik=SIDIK_SKENARIO, param_sg=param_sg
)

if cache:
    hasil_skenario = cache["hasil"]
    print("Hasil eksperimen skenario dimuat dari file.")
else:
    print("File belum ada, eksperimen skenario dijalankan (bagian ini lama)...")
    hasil_skenario = jalankan_eksperimen()
    simpan_cache(
        "hasil_eksperimen_skenario_skipgram.joblib",
        sidik=SIDIK_SKENARIO, param_sg=param_sg,
        hasil=hasil_skenario
    )
    hasil_skenario.to_csv(
        jalur("hasil_eksperimen_skenario_skipgram.csv"), index=False, encoding="utf-8-sig"
    )
    print("Hasil eksperimen disimpan.")

display(hasil_skenario)

File belum ada, eksperimen skenario dijalankan (bagian ini lama)...
Skenario V1 selesai.
Skenario V2 selesai.
Skenario V3 selesai.
Skenario V4 selesai.
Hasil eksperimen disimpan.

,Skenario,Keterangan,Token unik,Jumlah kolom,Parameter terbaik,Akurasi CV,Akurasi data uji
0,V1,"Hapus tanda baca, hapus stopword",7459,50,"{'sg__vector_size': 50, 'sg__window': 5}",0.9812,1.0
1,V2,"Pertahankan tanda baca, hapus stopword",7498,50,"{'sg__vector_size': 50, 'sg__window': 5}",0.9812,1.0
2,V3,"Hapus tanda baca, pertahankan stopword",7568,100,"{'sg__vector_size': 100, 'sg__window': 10}",0.9812,1.0
3,V4,Pertahankan semua (tanpa pembersihan tambahan),7607,100,"{'sg__vector_size': 100, 'sg__window': 10}",0.9812,1.0

### 6.4 Ringkasan dan Cara Membaca Hasil

Tabel berikut meringkas **akurasi CV** (patokan utama) dan **akurasi data uji** untuk setiap skenario.

In [23]:
display(hasil_skenario[["Skenario", "Keterangan", "Token unik", "Jumlah kolom", "Akurasi CV", "Akurasi data uji"]])

tertinggi = hasil_skenario["Akurasi CV"].max()
skenario_terbaik = hasil_skenario[hasil_skenario["Akurasi CV"] == tertinggi]["Skenario"].tolist()
print(f"Skip-gram: akurasi CV tertinggi {tertinggi} pada skenario {', '.join(skenario_terbaik)}")

,Skenario,Keterangan,Token unik,Jumlah kolom,Akurasi CV,Akurasi data uji
0,V1,"Hapus tanda baca, hapus stopword",7459,50,0.9812,1.0
1,V2,"Pertahankan tanda baca, hapus stopword",7498,50,0.9812,1.0
2,V3,"Hapus tanda baca, pertahankan stopword",7568,100,0.9812,1.0
3,V4,Pertahankan semua (tanpa pembersihan tambahan),7607,100,0.9812,1.0

Skip-gram: akurasi CV tertinggi 0.9812 pada skenario V1, V2, V3, V4

Cara membaca hasil:

- Bandingkan keempat skenario berdasarkan **Akurasi CV** sebagai patokan utama, karena data uji hanya 40 berita (selisih satu berita sudah mengubah akurasi 2,5%).
- Jika selisih antar skenario kecil (di bawah sekitar 1 sampai 2%), kesimpulannya adalah perlakuan tanda baca dan stopword tidak berpengaruh berarti pada dataset ini.
- Kolom **Token unik** menunjukkan ukuran kosakata tiap skenario: V3 dan V4 lebih banyak karena stopword dipertahankan, dan V2 dan V4 mendapat token tambahan berupa tanda baca.
- Jumlah kolom fitur Skip-gram tetap sebesar `vector_size`, berapa pun jumlah token uniknya.

Preprocessing utama Skip-gram adalah V3. Jika skenario lain memberikan hasil yang jelas lebih baik, ubah `SKENARIO_PAKAI` pada bagian 7.1 lalu jalankan ulang. Fungsi preprocessing pada aplikasi klasifikasi berita harus memakai pengaturan skenario yang sama dengan model yang disimpan.

In [24]:
# 1. Apakah teks tiap skenario benar-benar berbeda?
display(ringkasan_skenario)

# 2. Parameter dan skor tiap skenario
display(hasil_skenario[["Skenario", "Parameter terbaik", "Akurasi CV", "Akurasi data uji"]])

,Skenario,Keterangan,Total token,Token unik
0,V1,"Hapus tanda baca, hapus stopword",52007,7459
1,V2,"Pertahankan tanda baca, hapus stopword",66936,7498
2,V3,"Hapus tanda baca, pertahankan stopword",67583,7568
3,V4,Pertahankan semua (tanpa pembersihan tambahan),82512,7607

,Skenario,Parameter terbaik,Akurasi CV,Akurasi data uji
0,V1,"{'sg__vector_size': 50, 'sg__window': 5}",0.9812,1.0
1,V2,"{'sg__vector_size': 50, 'sg__window': 5}",0.9812,1.0
2,V3,"{'sg__vector_size': 100, 'sg__window': 10}",0.9812,1.0
3,V4,"{'sg__vector_size': 100, 'sg__window': 10}",0.9812,1.0

## 7. Menyimpan Model

### 7.1 Menyimpan Skip-gram dan Naive Bayes

Model dilatih ulang menggunakan seluruh 200 berita dengan parameter Skip-gram terbaik dari skenario yang dipilih pada `SKENARIO_PAKAI` (bawaan V3, hasil bagian 6), kemudian disimpan menjadi dua file terpisah:

- `skipgram.model`: model Skip-gram dalam format bawaan gensim.
- `naive_bayes.joblib`: model Naive Bayes dalam format sklearn (`joblib`).

Kedua komponen disimpan terpisah karena kelas `SkipgramVectorizer` didefinisikan di notebook, sehingga menyimpan seluruh pipeline dengan `joblib` akan gagal saat dibuka kembali di aplikasi Streamlit.

In [25]:
import joblib

SKENARIO_PAKAI = "V1"   # preprocessing utama Skip-gram; ganti jika skenario lain jelas lebih baik (lihat bagian 6)

# Parameter Skip-gram terbaik untuk skenario yang dipilih
baris_sg = hasil_skenario[hasil_skenario["Skenario"] == SKENARIO_PAKAI].iloc[0]
param_terbaik = baris_sg["Parameter terbaik"]

X_final = df[f"teks_{SKENARIO_PAKAI}"]
y_final = df["label"]

# Latih ulang dengan parameter terbaik pada seluruh data
model_final = Pipeline([
    ("sg", SkipgramVectorizer()),
    ("nb", GaussianNB()),
]).set_params(**param_terbaik).fit(X_final, y_final)

sg_final = model_final.named_steps["sg"]
nb_final = model_final.named_steps["nb"]

# Simpan terpisah
sg_final.w2v_.save("skipgram.model")
joblib.dump(nb_final, "naive_bayes.joblib")

print("Skenario          :", SKENARIO_PAKAI, "-", KETERANGAN[SKENARIO_PAKAI])
print("Parameter terbaik :", param_terbaik)
print("Tersimpan         : skipgram.model dan naive_bayes.joblib")

Skenario          : V1 - Hapus tanda baca, hapus stopword
Parameter terbaik : {'sg__vector_size': 50, 'sg__window': 5}
Tersimpan         : skipgram.model dan naive_bayes.joblib

### 7.2 Menguji Model yang Disimpan

Model dimuat kembali dari file untuk memastikan alurnya berjalan: teks masuk, diproses, diubah menjadi vektor Skip-gram, lalu vektor tersebut diklasifikasikan oleh Naive Bayes.

In [26]:
w2v_load = Word2Vec.load("skipgram.model")
nb_load = joblib.load("naive_bayes.joblib")


def prediksi(teks):
    bersih = preprocess_teks(teks, **PENGATURAN[SKENARIO_PAKAI])
    vec = [w2v_load.wv[k] for k in bersih.split() if k in w2v_load.wv]
    vec = np.mean(vec, axis=0) if vec else np.zeros(w2v_load.vector_size)
    return nb_load.predict([vec])[0]


print(prediksi("Harga emas Antam naik, rupiah menguat terhadap dolar"))
print(prediksi("Marc Marquez juara MotoGP setelah balapan sengit"))

finance
sport