# 🌸 Scrapping Data

## 1. Instalasi Library

Pada tahap awal, dilakukan instalasi library yang digunakan untuk proses web scraping. Library `requests` digunakan untuk mengambil halaman website, sedangkan `beautifulsoup4` digunakan untuk membaca dan mengambil informasi dari struktur HTML halaman website.

In [52]:
%pip install requests beautifulsoup4

Requirement already satisfied: requests in c:\Users\acer\Documents\semester 7\enWebmining\Lib\site-packages (2.34.2)
Requirement already satisfied: beautifulsoup4 in c:\Users\acer\Documents\semester 7\enWebmining\Lib\site-packages (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\acer\Documents\semester 7\enWebmining\Lib\site-packages (from requests) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\acer\Documents\semester 7\enWebmining\Lib\site-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\acer\Documents\semester 7\enWebmining\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\acer\Documents\semester 7\enWebmining\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\acer\Documents\semester 7\enWebmining\Lib\site-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\acer\Documents\semester 7\enWebmining\Lib\site-packages (from beautifulsoup4) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

## 2. Import Library

Pada tahap ini, beberapa library di-import untuk membantu proses web scraping:

- `requests` digunakan untuk mengambil halaman website.
- `BeautifulSoup` digunakan untuk membaca dan mengambil data dari struktur HTML.
- `csv` digunakan untuk mengolah atau menyimpan data dalam format CSV.
- `time` digunakan untuk memberikan jeda waktu saat proses scraping.
- `urljoin` digunakan untuk menggabungkan URL agar menjadi link yang lengkap.

In [53]:
import requests
from bs4 import BeautifulSoup
import csv
import time
from urllib.parse import urljoin

## 3. Membuat Header Request

Pada tahap ini, dibuat `HEADERS` yang berisi `User-Agent` untuk memberi informasi bahwa request berasal dari browser seperti Chrome pada Windows. Penggunaan `User-Agent` membantu proses scraping agar request lebih mudah diterima oleh website dan tidak langsung dianggap sebagai request dari bot.

In [ ]:
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/131.0.0.0 Safari/537.36"
    )
}

## 4. Membuat Session

Pada tahap ini, dibuat `session` menggunakan `requests.Session()` agar koneksi dan pengaturan request dapat digunakan kembali selama proses scraping. Kemudian `HEADERS` yang sudah dibuat sebelumnya diterapkan ke session dengan `session.headers.update(HEADERS)`, sehingga setiap request otomatis menggunakan `User-Agent` tersebut.

In [55]:
session = requests.Session()
session.headers.update(HEADERS)

## 5. Mengambil URL Artikel

Pada tahap ini, dibuat fungsi `ambil_url_artikel()` untuk mengambil URL artikel dari website Detik.com. Fungsi ini mengambil artikel dari halaman utama kategori terlebih dahulu, kemudian dilanjutkan ke halaman indeks jika jumlah artikel yang dibutuhkan belum terpenuhi.

Prosesnya berjalan seperti berikut:

1. Fungsi menerima URL kategori, domain, dan jumlah URL yang ingin diambil.
2. Halaman pertama yang diakses adalah halaman utama kategori. Jika belum mendapatkan jumlah URL yang cukup, fungsi berpindah ke halaman indeks berikutnya.
3. Setiap halaman dibaca menggunakan `BeautifulSoup` untuk mencari semua link (`<a>`) yang tersedia.
4. Link kemudian diubah menjadi URL lengkap menggunakan `urljoin()`.
5. URL disaring berdasarkan domain dan pola `"/d-"` agar yang diambil hanya URL artikel Detik.
6. URL yang sudah pernah ditemukan tidak dimasukkan lagi sehingga tidak terjadi duplikasi.
7. Jika jumlah URL sudah mencapai target, proses pengambilan dihentikan.
8. Setelah selesai membaca satu halaman, program memberikan jeda 1 detik menggunakan `time.sleep(1)` sebelum melanjutkan ke halaman berikutnya.
9. Proses dibatasi maksimal sampai 30 halaman untuk mencegah scraping berjalan terus-menerus jika jumlah artikel yang ditemukan tidak mencukupi.

Hasil akhirnya berupa daftar URL artikel yang jumlahnya disesuaikan dengan nilai `jumlah` yang diberikan.

In [56]:
def ambil_url_artikel(url_kategori, domain, jumlah=100):
    """
    Mengambil URL artikel dari homepage dan
    halaman indeks sampai jumlah URL terpenuhi.
    """

    print(f"\nMengambil artikel dari: {url_kategori}")

    daftar_url = []
    halaman = 1

    while len(daftar_url) < jumlah:

        if halaman == 1:
            url = url_kategori
        else:
            url = f"{url_kategori.rstrip('/')}/indeks?page={halaman}"

        print(f"\nMengambil halaman {halaman}:")
        print(url)

        try:
            response = session.get(
                url,
                timeout=15
            )

            print("Status:", response.status_code)

        except requests.RequestException as error:
            print("Error:", error)
            halaman += 1
            continue

        if response.status_code != 200:
            print("Halaman gagal diakses.")
            halaman += 1
            continue

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        jumlah_sebelum = len(daftar_url)

        for link in soup.find_all("a", href=True):

            href = link["href"].strip()

            href = urljoin(url, href)

            if (
                domain in href
                and "/d-" in href
            ):

                href = href.split("#")[0]

                if href not in daftar_url:

                    daftar_url.append(href)

                    print(
                        f"  [{len(daftar_url)}/{jumlah}] "
                        f"{href}"
                    )

                if len(daftar_url) >= jumlah:
                    break

        jumlah_baru = len(daftar_url) - jumlah_sebelum

        print(
            f"Artikel baru dari halaman ini: "
            f"{jumlah_baru}"
        )

        if jumlah_baru == 0:
            print(
                "Tidak ada artikel baru di halaman ini."
            )

        halaman += 1

        time.sleep(1)

        if halaman > 30:
            print("Batas halaman tercapai.")
            break

    print("\n======================================")
    print(
        f"Total URL {domain}: "
        f"{len(daftar_url)}"
    )
    print("======================================")

    return daftar_url[:jumlah]

## 6. Menguji Pengambilan URL Artikel Sport

Pada tahap ini, URL halaman utama Sport Detik disimpan ke dalam variabel `sport_url`. Selanjutnya, fungsi `ambil_url_artikel()` digunakan untuk mengambil 5 URL artikel dari kategori Sport dengan domain `sport.detik.com`. Data URL tersebut disimpan di dalam variabel `url_test` untuk mengecek apakah proses pengambilan artikel sudah berjalan sesuai yang diharapkan.

In [57]:
sport_url = "https://sport.detik.com/"

In [58]:
url_test = ambil_url_artikel(
    sport_url,
    "sport.detik.com",
    5
)

Mengambil artikel dari: https://sport.detik.com/

Mengambil halaman 1:
https://sport.detik.com/
Status: 200
  [1/5] https://sport.detik.com/raket/d-8653585/asian-games-2026-putri-kw-pede-dengan-komposisi-beregu-putri
  [2/5] https://sport.detik.com/basket/d-8649812/derrick-michael-wujudkan-mimpi-masa-kecil-tampil-di-asian-games-2026
  [3/5] https://sport.detik.com/moto-gp/d-8652425/dokter-perkirakan-kondisi-lengan-marc-marquez-sekitar-50-persen
  [4/5] https://sport.detik.com/raket/d-8653493/tekad-alwi-farhan-lampaui-batas-di-asian-games-2026
  [5/5] https://sport.detik.com/moto-gp/d-8650852/jadwal-motogp-san-marino-2026-misi-marc-marquez-kejar-jorge-martin
Artikel baru dari halaman ini: 5

======================================
Total URL sport.detik.com: 5
======================================

## 7. Mengambil Isi Berita

Pada tahap ini, dibuat fungsi `ambil_isi_berita()` yang digunakan untuk mengambil isi teks dari halaman artikel Detik berdasarkan URL yang sudah didapatkan sebelumnya. Fungsi ini juga membersihkan bagian-bagian halaman yang tidak diperlukan supaya data yang diperoleh hanya berupa isi berita.

Proses yang dilakukan dalam fungsi ini yaitu:

1. **Membuka halaman artikel**  
   URL artikel diakses menggunakan `session.get()` dengan batas waktu 15 detik. Jika halaman tidak bisa dibuka atau statusnya bukan `200`, fungsi akan mengembalikan data kosong.

2. **Mencari bagian isi berita**  
   Setelah halaman berhasil dibuka, `BeautifulSoup` digunakan untuk membaca struktur HTML. Program kemudian mencoba beberapa selector seperti `.detail__body-text` dan `.detail__body` untuk menemukan bagian yang berisi artikel.

3. **Membersihkan isi artikel**  
   Elemen yang tidak diperlukan seperti `script`, `style`, `iframe`, gambar, video, dan tombol dihapus menggunakan `decompose()`. Hal ini dilakukan agar elemen-elemen tersebut tidak ikut masuk ke dalam data berita.

4. **Mengambil dan merapikan teks**  
   Teks dari bagian artikel diambil menggunakan `get_text()`. Setelah itu, spasi yang berlebihan dirapikan sehingga isi berita menjadi lebih bersih dan mudah digunakan sebagai dataset.

Terakhir, fungsi mengembalikan isi berita yang sudah dibersihkan. Jika terjadi error saat mengambil halaman, fungsi akan mengembalikan data kosong dan proses scraping dapat dilanjutkan ke artikel berikutnya.

In [59]:
def ambil_isi_berita(url):
    """
    Membuka halaman artikel dan mengambil isi berita.
    """

    try:

        response = session.get(
            url,
            timeout=15
        )

        if response.status_code != 200:

            print(
                "Gagal membuka:",
                response.status_code
            )

            return ""

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        selector_list = [
            ".detail__body-text",
            ".detail__body",
            "div.detail__body-text",
            "article"
        ]

        artikel = None

        for selector in selector_list:

            artikel = soup.select_one(selector)

            if artikel is not None:
                break

        if artikel is None:
            return ""

        for tag in artikel.find_all(
            [
                "script",
                "style",
                "iframe",
                "img",
                "video",
                "figure",
                "button"
            ]
        ):

            tag.decompose()

        isi = artikel.get_text(
            " ",
            strip=True
        )

        isi = " ".join(
            isi.split()
        )

        return isi

    except requests.RequestException as error:

        print(
            "Error:",
            error
        )

        return ""

## 8. Menyiapkan Dataset

Pada tahap ini, disiapkan tempat untuk menyimpan seluruh data berita yang nantinya akan dikumpulkan. Variabel `dataset` berupa list kosong yang akan digunakan untuk menampung data setiap artikel, sedangkan `id_data` digunakan sebagai nomor ID untuk setiap data dan dimulai dari angka 1.

In [60]:
# Menyiapkan list untuk dataset akhir
dataset = []

# ID data dimulai dari 1
id_data = 1

## 9. Mengambil 100 Berita Sport

Pada tahap ini, URL berita Sport yang sudah dikumpulkan sebelumnya diproses satu per satu untuk mengambil isi beritanya. Program akan terus mengambil berita sampai mendapatkan 100 artikel yang berhasil diproses.

Alurnya yaitu:

1. `jumlah_sport` digunakan untuk menghitung berapa berita Sport yang sudah berhasil diambil.
2. Program membaca URL berita dari `data_sport` satu per satu.
3. Isi berita diambil menggunakan fungsi `ambil_isi_berita()`.
4. Jika isi berita berhasil diambil, data disimpan ke dalam `dataset` dengan tiga informasi:
   - `id` sebagai nomor data.
   - `isi_berita` sebagai teks berita.
   - `label` dengan nilai `"sport"`.
5. Setiap berita yang berhasil akan menambah `jumlah_sport` dan `id_data`.
6. Progress ditampilkan setiap 25 berita agar bisa melihat perkembangan proses scraping.
7. Jika isi berita gagal diambil, URL tersebut dilewati dan program lanjut ke berita berikutnya.
8. Setelah jumlah berita berhasil mencapai 100, proses dihentikan.

Dengan proses ini, data Sport yang masuk ke dataset hanya berasal dari artikel yang isi beritanya berhasil diambil.

In [61]:
# Menghitung jumlah berita Sport yang berhasil
jumlah_sport = 0

# Memproses URL berita Sport
for berita in data_sport:

    # Berhenti jika sudah mendapatkan 100 berita
    if jumlah_sport >= 100:
        break

    # Mengambil isi berita
    isi = ambil_isi_berita(
        berita["link"]
    )

    # Jika isi berita berhasil diambil
    if isi:

        data = {
            "id": id_data,
            "isi_berita": isi,
            "label": "sport"
        }

        # Memasukkan data ke dataset
        dataset.append(data)

        # Menambah jumlah berita berhasil
        jumlah_sport = jumlah_sport + 1

        # Menambah ID
        id_data = id_data + 1

        # Menampilkan progres setiap 25 data
        if jumlah_sport % 25 == 0:
            print(
                "Sport berhasil:",
                jumlah_sport,
                "/ 100"
            )

    else:

        # Jika gagal, lanjut ke URL berikutnya
        print("Sport gagal, lanjut ke berita berikutnya...")


# Menampilkan hasil Sport
print("Jumlah berita Sport berhasil:", jumlah_sport)

Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport berhasil: 25 / 100
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport berhasil: 50 / 100
Sport berhasil: 75 / 100
Sport gagal, lanjut ke berita berikutnya...
Sport gagal, lanjut ke berita berikutnya...
Sport berhasil: 100 / 100
Jumlah berita Sport berhasil: 100

In [62]:
url_contoh = url_test[0]

isi_contoh = ambil_isi_berita(url_contoh)

print(isi_contoh)

Jakarta - Putri Kusuma Wardani percaya diri dengan komposisi beregu putri yang dipilih PBSI untuk Asian Games 2026. Dia juga menyebut chemistry satu sama lain sudah klop. Bulutangkis Indonesia mengirimkan 20 wakil untuk tampil di Aichi-Nagoya, 19 September hingga 4 Oktober mendatang. 10 Atlet di antaranya merupakan sektor beregu putri. Yaitu Putri KW, Thalita R. Wiryawan, Ni Kadek Dhinda, Mutiara Ayu Puspitasari, Rachel Allessya Rose, Febi Setianingrum, Febriana Dwipuji Kusuma, Meilysa Trias Puspitasari, Siti Fadia Silva Ramadhanti, dan Nita Violina Marwah. SCROLL TO CONTINUE WITH CONTENT Baca juga: Tekad Alwi Farhan Lampaui Batas di Asian Games 2026 Putri menilai komposisi skuad bulutangkis Indonesia yang mengombinasikan pemain senior dan junior, tidak menemukan kendala dalam membangun koneksi di dalam tim. ADVERTISEMENT Pengalaman berlaga bersama dalam beberapa kejuaraan beregu sebelumnya dinilai telah membentuk kekompakan antar-atlet. "Dengan tim komposisi yang ada cukup kuat sih. Kita juga sudah lumayan dua atau tiga kali beregu bersama-sama, jadi sudah ketemu chemistry-nya di antara satu dan yang lain, baik tunggal maupun ganda," kata Putri dalam keterangannya dikutip Selasa (8/9/2026). Tak hanya itu, seluruh rangkaian program latihan di Pelatnas sejauh ini berjalan dengan lancar dan kondusif. Sampai menjelang hari keberangkatan menuju Jepang, porsi latihan tim nasional kini lebih difokuskan pada penguatan di masing-masing sektor di bawah arahan tim pelatih. "Yang pasti, kekurangan dari pertandingan sebelumnya menuju pertandingan Asian Games lebih ditingkatkan lagi," tambahnya. Baca juga: Ini Dia 20 Pebulutangkis Indonesia di Asian Games 2026 Terkait peta persaingan di Asian Games 2026, Putri KW menilai kekuatan di sektor tunggal putri kawasan Asia tergolong sangat merata. Dia mewaspadai kekuatan para pemain dari negara-negara papan atas seperti China, Jepang, dan Korea Selatan. "Kalau kekuatan sendiri di Asian Games menurut aku cukup merata ya dari Asia sendiri, terutama dari China, Jepang, dan Korea Selatan sih cukup kuat," tuturnya. Pebulutangkis peringkat ke-7 dunia itu memasang target tinggi pada ajang Asian Games 2026. Secara pribadi, Putri berambisi untuk dapat melangkah hingga ke babak akhir dan berdiri di atas podium. Hal ini juga sejalan dengan target medali yang dicanangkan oleh PP PBSI. "Harapannya semoga tim bulu tangkis Indonesia bisa mendapatkan medali, dan terutama untuk pribadi aku sendiri, aku bisa menyumbangkan medali untuk Indonesia di ajang Asian Games," pungkas Putri. Lihat juga Video; Hong Kong Open 2024: Sabar/Reza dan Putri KW Tumbang di Final [Gambas:Video 20detik] (mcy/aff) ... Tautan telah disalin asian games 2026 putri kusuma wardani pbsi

## 10. Mengecek Hasil Dataset

Pada tahap ini, data yang sudah dikumpulkan diubah menjadi `DataFrame` menggunakan `pandas` agar lebih mudah dilihat dan diolah.

Setelah itu, program menampilkan jumlah seluruh data menggunakan `len(df)` dan menghitung jumlah data berdasarkan label menggunakan `value_counts()`. Dari hasil ini, dapat diketahui apakah jumlah berita Sport dan Finance sudah sesuai dengan target yang ditentukan.

In [63]:
# Mengubah dataset menjadi DataFrame
df = pd.DataFrame(dataset)

# Menampilkan jumlah total data
print("Jumlah total data:", len(df))

# Menampilkan jumlah masing-masing label
print(df["label"].value_counts())

Jumlah total data: 100
label
sport    100
Name: count, dtype: int64

Pada tahap ini, dataset diubah menjadi `DataFrame` menggunakan `pd.DataFrame(dataset)`. Setelah itu, `len(df)` digunakan untuk menghitung jumlah seluruh data yang sudah terkumpul. Hasilnya ditampilkan untuk memastikan jumlah data yang didapat sudah sesuai dengan target.

In [64]:
# Mengubah dataset menjadi DataFrame
df = pd.DataFrame(dataset)

# Menampilkan jumlah data
print("Jumlah total data:", len(df))

Jumlah total data: 100

## 11. Membuat Fungsi Crawling

Pada tahap ini, dibuat fungsi `crawling_kategori()` untuk menggabungkan proses pengambilan URL dan isi berita menjadi satu alur. Fungsi ini bisa digunakan untuk beberapa kategori berita, seperti Sport dan Finance, sehingga tidak perlu membuat kode yang sama berulang kali.

Alurnya yaitu:

1. Fungsi menerima URL kategori, domain, label berita, dan jumlah berita yang ingin diambil.
2. Fungsi `ambil_url_artikel()` dipanggil untuk mendapatkan daftar URL sesuai jumlah yang ditentukan.
3. Setiap URL diproses satu per satu menggunakan fungsi `ambil_isi_berita()`.
4. Jika isi berita berhasil diambil, teks berita dan label dimasukkan ke dalam list `data`.
5. Program menampilkan progres setiap artikel yang sedang diproses, termasuk jumlah karakter isi berita.
6. Jika isi berita tidak ditemukan, data tersebut dilewati dan proses dilanjutkan ke URL berikutnya.
7. `time.sleep(1)` digunakan untuk memberi jeda 1 detik setelah memproses setiap artikel.
8. Proses berhenti jika jumlah berita yang berhasil sudah mencapai target.

Setelah selesai, fungsi mengembalikan `data` yang berisi isi berita beserta label kategorinya. Dengan fungsi ini, proses crawling Sport dan Finance nantinya bisa dilakukan dengan cara yang lebih praktis.

In [ ]:

# Code Cell — Fungsi Crawling

def crawling_kategori(
    url_kategori,
    domain,
    label,
    jumlah=100
):

    print("\n======================================")
    print(f"CRAWLING {label.upper()}")
    print("Target:", jumlah, "berita")
    print("======================================")

    urls = ambil_url_artikel(
        url_kategori,
        domain,
        jumlah
    )

    print(
        f"\nURL yang akan diproses: "
        f"{len(urls)}"
    )

    data = []

    for i, url in enumerate(
        urls,
        start=1
    ):

        print(
            f"\n[{i}/{len(urls)}] "
            f"Mengambil berita {label}..."
        )

        isi = ambil_isi_berita(url)

        if isi:

            data.append({
                "isi_berita": isi,
                "label": label
            })

            print(
                "✓ Berhasil | "
                f"{len(isi)} karakter"
            )

        else:

            print(
                "✗ Isi berita tidak ditemukan"
            )

        time.sleep(1)

        if len(data) >= jumlah:
            break

    print("\n======================================")
    print(
        f"Berita {label} berhasil: "
        f"{len(data)}"
    )
    print("======================================")

    return data

## 12. Menjalankan Proses Crawling

### 12.1 Menentukan URL Kategori

Pada tahap ini, ditentukan URL halaman utama untuk kategori Sport dan Finance pada Detik.com. URL tersebut disimpan ke dalam variabel `sport_url` dan `finance_url` yang nantinya digunakan sebagai alamat awal dalam proses crawling berita.

In [66]:
sport_url = "https://sport.detik.com/"
finance_url = "https://finance.detik.com/"

### 12.2 Crawling Berita Sport

Pada tahap ini, dilakukan pengujian proses crawling untuk kategori Sport dengan target sebanyak 5 berita. Fungsi `crawling_kategori()` digunakan dengan memasukkan URL Sport, domain `sport.detik.com`, label `sport`, dan jumlah berita yang ingin diambil sebanyak 5. Hasil crawling disimpan ke dalam variabel `data_sport` untuk digunakan pada tahap berikutnya.

In [67]:
data_sport = crawling_kategori(
    sport_url,
    "sport.detik.com",
    "sport",
    5
)

======================================
CRAWLING SPORT
Target: 5 berita
======================================

Mengambil artikel dari: https://sport.detik.com/

Mengambil halaman 1:
https://sport.detik.com/
Status: 200
  [1/5] https://sport.detik.com/raket/d-8653585/asian-games-2026-putri-kw-pede-dengan-komposisi-beregu-putri
  [2/5] https://sport.detik.com/basket/d-8649812/derrick-michael-wujudkan-mimpi-masa-kecil-tampil-di-asian-games-2026
  [3/5] https://sport.detik.com/moto-gp/d-8652425/dokter-perkirakan-kondisi-lengan-marc-marquez-sekitar-50-persen
  [4/5] https://sport.detik.com/raket/d-8653493/tekad-alwi-farhan-lampaui-batas-di-asian-games-2026
  [5/5] https://sport.detik.com/moto-gp/d-8650852/jadwal-motogp-san-marino-2026-misi-marc-marquez-kejar-jorge-martin
Artikel baru dari halaman ini: 5

======================================
Total URL sport.detik.com: 5
======================================

URL yang akan diproses: 5

[1/5] Mengambil berita sport...
✓ Berhasil | 2720 karakter

[2/5] Mengambil berita sport...
✓ Berhasil | 2749 karakter

[3/5] Mengambil berita sport...
✓ Berhasil | 2191 karakter

[4/5] Mengambil berita sport...
✓ Berhasil | 2239 karakter

[5/5] Mengambil berita sport...
✓ Berhasil | 3619 karakter

======================================
Berita sport berhasil: 5
======================================

### 12.3 Crawling Berita Finance

Pada tahap ini, dilakukan pengujian proses crawling untuk kategori Finance dengan target sebanyak 5 berita. Fungsi `crawling_kategori()` digunakan dengan URL Finance, domain `finance.detik.com`, label `finance`, dan jumlah berita sebanyak 5. Hasil crawling disimpan ke dalam variabel `data_finance` untuk digunakan pada tahap berikutnya.

In [68]:
data_finance = crawling_kategori(
    finance_url,
    "finance.detik.com",
    "finance",
    5
)

======================================
CRAWLING FINANCE
Target: 5 berita
======================================

Mengambil artikel dari: https://finance.detik.com/

Mengambil halaman 1:
https://finance.detik.com/
Status: 200
  [1/5] https://finance.detik.com/moneter/d-8655958/duit-apbn-dipakai-biayai-buka-rekening-bank-purbaya-buka-suara
  [2/5] https://finance.detik.com/moneter/d-8655766/masyarakat-dibuatkan-rekening-saldo-awal-rp-50-ribu-sumber-apbn-rp-11-t
  [3/5] https://finance.detik.com/berita-ekonomi-bisnis/d-8655007/pm-singapura-sumbangkan-kenaikan-gaji-rp-24-m-selama-5-tahun
  [4/5] https://finance.detik.com/berita-ekonomi-bisnis/d-8654941/harga-emas-antam-makin-jatuh
  [5/5] https://finance.detik.com/berita-ekonomi-bisnis/d-8654769/ratusan-penerbangan-di-inggris-delay-batal-ada-apa
Artikel baru dari halaman ini: 5

======================================
Total URL finance.detik.com: 5
======================================

URL yang akan diproses: 5

[1/5] Mengambil berita finance...
✓ Berhasil | 1707 karakter

[2/5] Mengambil berita finance...
✓ Berhasil | 1468 karakter

[3/5] Mengambil berita finance...
✓ Berhasil | 2431 karakter

[4/5] Mengambil berita finance...
✓ Berhasil | 1898 karakter

[5/5] Mengambil berita finance...
✓ Berhasil | 2274 karakter

======================================
Berita finance berhasil: 5
======================================

### 12.4 Crawling 100 Berita Sport

Setelah proses pengujian berhasil dilakukan, tahap berikutnya adalah mengambil data utama untuk kategori Sport sebanyak 100 berita. Fungsi `crawling_kategori()` digunakan kembali dengan target 100 berita, kemudian hasil crawling disimpan ke dalam variabel `data_sport`.

In [ ]:
data_sport = crawling_kategori(
    sport_url,
    "sport.detik.com",
    "sport",
    100
)

======================================
CRAWLING SPORT
Target: 100 berita
======================================

Mengambil artikel dari: https://sport.detik.com/

Mengambil halaman 1:
https://sport.detik.com/
Status: 200
  [1/100] https://sport.detik.com/raket/d-8653585/asian-games-2026-putri-kw-pede-dengan-komposisi-beregu-putri
  [2/100] https://sport.detik.com/basket/d-8649812/derrick-michael-wujudkan-mimpi-masa-kecil-tampil-di-asian-games-2026
  [3/100] https://sport.detik.com/moto-gp/d-8652425/dokter-perkirakan-kondisi-lengan-marc-marquez-sekitar-50-persen
  [4/100] https://sport.detik.com/raket/d-8653493/tekad-alwi-farhan-lampaui-batas-di-asian-games-2026
  [5/100] https://sport.detik.com/moto-gp/d-8650852/jadwal-motogp-san-marino-2026-misi-marc-marquez-kejar-jorge-martin
  [6/100] https://sport.detik.com/sport-lain/d-8655872/pelatih-timnas-voli-putra-ri-targetkan-medali-di-asian-games-2026
  [7/100] https://sport.detik.com/sport-lain/d-8656039/ketum-koi-memastikan-atlet-terlayani-dengan-baik-di-nagoya
  [8/100] https://sport.detik.com/sport-lain/d-8655779/asian-games-2026-prabowo-janjikan-bonus-rp-3-m-untuk-peraih-emas
  [9/100] https://sport.detik.com/sepakbola/uefa/d-8655868/liverpool-vs-atletico-the-reds-dibayangi-rekor-buruk-iraola-atas-simeone
  [10/100] https://sport.detik.com/sepakbola/liga-inggris/d-8655863/enzo-fernandez-bahagia-banget-tetap-dilatih-maresca
  [11/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8655861/persib-sadari-pertahanan-persija-jauh-lebih-kukuh
  [12/100] https://sport.detik.com/sepakbola/uefa/d-8655864/lamine-yamal-bisa-jadi-penentu-hasil-laga-sendirian
  [13/100] https://sport.detik.com/sepakbola/uefa/d-8655785/mbappe-tegaskan-saat-ini-liga-champions-lebih-penting-daripada-ballon-dor
  [14/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8655858/persija-panaskan-mesin-jelang-jamu-persib
  [15/100] https://sport.detik.com/sepakbola/uefa/d-8655782/maresca-minta-pemain-city-kurang-kurangi-backpass-ke-donnarumma
  [16/100] https://sport.detik.com/sepakbola/bola-dunia/d-8655780/presiden-fifa-vs-100-ribu-aduan
  [17/100] https://sport.detik.com/sportstyle/d-8655787/dari-hyrox-ke-10k-fanny-ghassani-pilih-pace-santai
  [18/100] https://sport.detik.com/sepakbola/liga-inggris/d-8655272/xabi-alonso-redam-isu-estevao-mau-cabut-dari-chelsea
  [19/100] https://sport.detik.com/sepakbola/uefa/d-8655109/mourinho-real-madrid-vs-inter-milan-pertandingan-gila
  [20/100] https://sport.detik.com/sepakbola/uefa/d-8655331/luis-enrique-nggak-mau-ingat-ingat-psg-juara-bertahan-liga-champions
  [21/100] https://sport.detik.com/sepakbola/uefa/d-8655327/arsenal-masih-100-pede-banget-tantang-napoli
  [22/100] https://sport.detik.com/sepakbola/bola-dunia/d-8655334/raheem-sterling-tolak-tawaran-main-di-klub-ini
  [23/100] https://sport.detik.com/sport-lain/d-8655636/rizki-juniansyah-siap-debut-di-asian-games-2026-naik-kelas-ke-85-kg
  [24/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8655338/head-to-head-persija-vs-persib-10-laga-terbaru-macan-kemayoran-kurang-oke
  [25/100] https://sport.detik.com/sepakbola/bola-dunia/d-8655329/legenda-timnas-prancis-sebut-mbappe-tak-layak-raih-ballon-dor-2026
  [26/100] https://sport.detik.com/sepakbola/uefa/d-8655261/mourinho-inter-milan-tim-terbaik-italia
  [27/100] https://sport.detik.com/sepakbola/uefa/d-8655324/napoli-vs-arsenal-calafiori-nantikan-gemuruh-stadion-maradona
  [28/100] https://sport.detik.com/sepakbola/uefa/d-8655270/yamal-cuma-kurang-trofi-liga-champions-bertekad-juara-di-musim-ini
  [29/100] https://sport.detik.com/sepakbola/uefa/d-8655252/inter-milan-pulang-dari-bernabeu-dengan-kepala-tegak
  [30/100] https://sport.detik.com/sepakbola/uefa/d-8655195/arsenal-mau-buka-liga-champions-dengan-wow
  [31/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8655335/persija-vs-persib-perang-penggawa-timnas-indonesia
  [32/100] https://sport.detik.com/sepakbola/uefa/d-8655223/mourinho-selamatkan-vinicius-dari-cemooh-suporter-real-madrid
  [33/100] https://sport.detik.com/sepakbola/uefa/d-8655193/inter-milan-membayar-mahal-blunder-blunder-lini-belakang
  [34/100] https://sport.detik.com/sport-lain/d-8655308/cdm-todotua-kami-monitoring-terus-kondisi-di-nagoya
  [35/100] https://sport.detik.com/sepakbola/uefa/d-8655182/ngerinya-haaland-di-liga-champions-satu-gol-per-laga
  [36/100] https://sport.detik.com/sepakbola/bola-dunia/d-8655208/mengapa-lionel-messi-masuk-nominasi-ballon-dor-2026
  [37/100] https://sport.detik.com/sport-lain/d-8655303/asian-games-2026-banjir-landa-nagoya-menpora-yakin-jepang-punya-plan-b
  [38/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8655279/fix-persija-menjamu-persib-di-sugbk
  [39/100] https://sport.detik.com/sepakbola/liga-indonesia/d-8655111/australia-gagal-ke-piala-asia-u-20-pemain-diaspora-indonesia-dibawa-bawa
  [40/100] https://sport.detik.com/sepakbola/uefa/d-8655082/beda-nasib-dua-mbappe
  [41/100] https://sport.detik.com/sepakbola/uefa/d-8654252/napoli-vs-arsenal-il-partenopei-pincang
  [42/100] https://sport.detik.com/sepakbola/uefa/d-8654896/haaland-samai-aguero-jadi-top-skor-man-city-di-liga-champions
  [43/100] https://sport.detik.com/sepakbola/liga-inggris/d-8654259/michael-carrick-puas-dengan-performa-rashford
  [44/100] https://sport.detik.com/sport-lain/d-8655067/ketum-koi-dan-menpora-mengukuhkan-tim-indonesia-untuk-asian-games-2026
  [45/100] https://sport.detik.com/sepakbola/uefa/d-8654863/liga-champions-john-mcginn-cetak-gol-pembuka-musim-gabung-messi-ronaldo
  [46/100] https://sport.detik.com/sepakbola/bola-dunia/d-8654333/lautaro-martinez-hanya-bisa-ucapkan-terima-kasih-kepada-lionel-messi
  [47/100] https://sport.detik.com/sepakbola/uefa/d-8654846/courtois-masuk-klub-100-liga-champions-kiper-ke-8-dalam-daftar
  [48/100] https://sport.detik.com/sepakbola/liga-italia/d-8654332/milan-punya-gaya-main-yang-jelas-di-bawah-asuhan-amorim
  [49/100] https://sport.detik.com/sepakbola/uefa/d-8654841/jadwal-liga-champions-malam-ini-arsenal-liverpool-dan-barcelona-main
  [50/100] https://sport.detik.com/sepakbola/uefa/d-8654792/chivu-tak-marah-inter-bikin-salah-yang-penting-reaksinya
  [51/100] https://sport.detik.com/sepakbola/uefa/d-8654832/top-skor-liga-champions-haaland-guirassy-dan-bartra-sama-sama-2-gol
  [52/100] https://sport.detik.com/sepakbola/liga-spanyol/d-8654771/messi-segera-akuisisi-klub-divisi-dua-spanyol
  [53/100] https://sport.detik.com/sepakbola/bola-dunia/d-8654748/lamine-yamal-tak-akan-memohon-agar-menang-ballon-dor
  [54/100] https://sport.detik.com/moto-gp/d-8654776/motogp-san-marino-2026-jaga-puncak-klasemen-bukan-prioritas-jorge-martin
Artikel baru dari halaman ini: 54

Mengambil halaman 2:
https://sport.detik.com/indeks?page=2
Status: 200
  [55/100] https://sport.detik.com/sport-lain/d-8653123/wrt-32-di-lone-star-le-mans-startnya-sudah-bagus-tapi
  [56/100] https://sport.detik.com/sportstyle/d-8653121/setelah-9-tahun-gelar-basket-kini-ljk-2026-rambah-padel
  [57/100] https://sport.detik.com/sportstyle/d-8653076/ngedadak-padel-ketika-padel-jadi-ajang-reuni
  [58/100] https://sport.detik.com/sportstyle/d-8653072/menjaga-gaya-hidup-sehat-lewat-hyrox
  [59/100] https://sport.detik.com/raket/d-8653071/mens-world-tennis-championship-3-wakil-ri-gagal-ke-babak-utama-seri-v
  [60/100] https://sport.detik.com/sport-lain/d-8653014/debut-di-rok-cup-indonesia-2026-barra-ghaisan-torehkan-catatan-positif
  [61/100] https://sport.detik.com/moto-gp/d-8652587/motogp-san-marino-antusiasme-bezzecchi-balapan-di-rumah-sendiri
  [62/100] https://sport.detik.com/f1/d-8651642/mamma-mia-antonelli
  [63/100] https://sport.detik.com/raket/d-8651603/mens-world-tennis-championship-karan-singh-juara-seri-iv
  [64/100] https://sport.detik.com/sportstyle/d-8651462/jete-run-festival-2026-selesai-masuk-rekor-muri
  [65/100] https://sport.detik.com/advertorial-news-block/d-8651455/menkomdigi-imbau-warga-waspadai-dampak-erupsi-anak-krakatau
  [66/100] https://sport.detik.com/f1/d-8651436/hasil-f1-gp-italia-2026-kimi-antonelli-menang-mercedes-1-2
  [67/100] https://sport.detik.com/sport-lain/d-8651374/wec-2026-sean-gelael-balapan-di-austin-dini-hari-start-p7
  [68/100] https://sport.detik.com/moto-gp/d-8651046/ktm-suka-antusiasme-luca-marini
  [69/100] https://sport.detik.com/moto-gp/d-8650870/crutchlow-pilih-ai-ogura-jadi-favorit-setelah-marc-marquez-ini-alasannya
  [70/100] https://sport.detik.com/sport-lain/d-8650342/wec-2026-wrt-32-meraba-cota-dari-hasil-free-practice
  [71/100] https://sport.detik.com/raket/d-8650339/mens-world-tennis-championship-rafalentino-ethan-gagal-juara
Artikel baru dari halaman ini: 17

Mengambil halaman 3:
https://sport.detik.com/indeks?page=3
Status: 200
  [72/100] https://sport.detik.com/sportstyle/d-8650215/minala-cup-padel-diikuti-lebih-dari-300-peserta
  [73/100] https://sport.detik.com/sport-lain/d-8650061/lewat-buku-eks-judoka-tuang-buah-pikiran-untuk-kemajuan-olahraga-nasional
  [74/100] https://sport.detik.com/basket/d-8649778/asian-games-2026-timnas-basket-masuk-grup-neraka-cdm-optimistis
  [75/100] https://sport.detik.com/sport-lain/d-8649669/kalah-di-perempatfinal-avc-beach-continental-ini-kata-bintang-sofyan
  [76/100] https://sport.detik.com/sport-lain/d-8649199/wec-2026-paruh-kedua-musim-dimulai-team-wrt-32-lebih-pede
  [77/100] https://sport.detik.com/raket/d-8649186/mens-world-tennis-championship-ganda-indonesia-tembus-final
  [78/100] https://sport.detik.com/sport-lain/d-8649149/timnas-voli-putra-dan-putri-indonesia-bidik-8-besar-asian-games-2026
  [79/100] https://sport.detik.com/sport-lain/d-8649165/bali-bakal-gelar-turnamen-catur-internasional-akhir-oktober
  [80/100] https://sport.detik.com/fotosport/d-8648227/kyrchyn-gorge-jadi-panggung-world-nomad-games
  [81/100] https://sport.detik.com/raket/d-8649124/hasil-china-masters-2026-sabar-reza-out-wakil-indonesia-habis
  [82/100] https://sport.detik.com/moto-gp/d-8648849/pol-acosta-akan-menang-balapan-dan-jadi-juara-dunia-cuma-soal-waktu
  [83/100] https://sport.detik.com/sport-lain/d-8648336/avc-continental-2026-bintang-sofyan-hadapi-selandia-baru-di-16-besar
  [84/100] https://sport.detik.com/sport-lain/d-8648160/pemanasan-timnas-basket-3x3-di-taiwan-jelang-asian-games-2026
  [85/100] https://sport.detik.com/sportstyle/d-8647385/belum-pernah-ikut-kelas-yoga-yoga-outdoor-ini-cocok-untuk-beginner
  [86/100] https://sport.detik.com/raket/d-8647457/mens-world-tennis-championship-nathan-barki-ke-perempatfinal
  [87/100] https://sport.detik.com/sportstyle/d-8647394/bakal-ada-jakarta-vertical-run-2026-bulan-november
  [88/100] https://sport.detik.com/raket/d-8647441/hasil-china-masters-2026-sabar-reza-menang-melaju-ke-perempatfinal
  [89/100] https://sport.detik.com/sport-lain/d-8647346/dki-jakarta-gelar-pon-pantai-2026-bulan-november
  [90/100] https://sport.detik.com/moto-gp/d-8647200/marc-marquez-makin-dekat-jorge-martin-akan-lawan
Artikel baru dari halaman ini: 19

Mengambil halaman 4:
https://sport.detik.com/indeks?page=4
Status: 200
  [91/100] https://sport.detik.com/moto-gp/d-8646970/gelar-juara-motogp-2026-jadi-ujian-ketahanan-marc-marquez
  [92/100] https://sport.detik.com/raket/d-8647100/hasil-china-masters-2026-leo-daniel-kena-comeback-keok-di-16-besar
  [93/100] https://sport.detik.com/sport-lain/d-8646915/kolaborasi-dengan-npc-kemenpora-genjot-pembinaan-atlet-disabilitas
  [94/100] https://sport.detik.com/sport-lain/d-8646269/jalan-panjang-bilal-hasan-menuju-titel-ufc
  [95/100] https://sport.detik.com/raket/d-8646249/hasil-china-masters-2026-jojo-terhenti-di-babak-kedua
  [96/100] https://sport.detik.com/sportstyle/d-8645952/spesialnya-jakarta-international-10k-tahun-ini
  [97/100] https://sport.detik.com/raket/d-8645946/mens-world-tennis-championship-rafalentino-dan-anthony-ke-babak-kedua
  [98/100] https://sport.detik.com/g-sport/d-8645920/atlet-bukan-satu-satunya-kunci-kemajuan-olahraga-nasional
  [99/100] https://sport.detik.com/moto-gp/d-8645850/agar-motogp-indonesia-2026-sukses-di-dalam-dan-luar-lintasan
  [100/100] https://sport.detik.com/moto-gp/d-8645527/motogp-2026-aprilia-kian-termotivasi-kalahkan-marc-marquez
Artikel baru dari halaman ini: 10

======================================
Total URL sport.detik.com: 100
======================================

URL yang akan diproses: 100

[1/100] Mengambil berita sport...
✓ Berhasil | 2720 karakter

[2/100] Mengambil berita sport...
✓ Berhasil | 2749 karakter

[3/100] Mengambil berita sport...
✓ Berhasil | 2191 karakter

[4/100] Mengambil berita sport...
✓ Berhasil | 2239 karakter

[5/100] Mengambil berita sport...
✓ Berhasil | 3619 karakter

[6/100] Mengambil berita sport...
✓ Berhasil | 2133 karakter

[7/100] Mengambil berita sport...
✓ Berhasil | 2958 karakter

[8/100] Mengambil berita sport...
✓ Berhasil | 1832 karakter

[9/100] Mengambil berita sport...
✓ Berhasil | 1886 karakter

[10/100] Mengambil berita sport...
✓ Berhasil | 1735 karakter

[11/100] Mengambil berita sport...
✓ Berhasil | 1979 karakter

[12/100] Mengambil berita sport...
✓ Berhasil | 2047 karakter

[13/100] Mengambil berita sport...
✓ Berhasil | 1609 karakter

[14/100] Mengambil berita sport...
✓ Berhasil | 2316 karakter

[15/100] Mengambil berita sport...
✓ Berhasil | 2032 karakter

[16/100] Mengambil berita sport...
✓ Berhasil | 1487 karakter

[17/100] Mengambil berita sport...
✓ Berhasil | 3743 karakter

[18/100] Mengambil berita sport...
✓ Berhasil | 1261 karakter

[19/100] Mengambil berita sport...
✓ Berhasil | 2025 karakter

[20/100] Mengambil berita sport...
✓ Berhasil | 1404 karakter

[21/100] Mengambil berita sport...
✓ Berhasil | 1899 karakter

[22/100] Mengambil berita sport...
✓ Berhasil | 1143 karakter

[23/100] Mengambil berita sport...
✓ Berhasil | 3032 karakter

[24/100] Mengambil berita sport...
✓ Berhasil | 2266 karakter

[25/100] Mengambil berita sport...
✓ Berhasil | 1799 karakter

[26/100] Mengambil berita sport...
✓ Berhasil | 1955 karakter

[27/100] Mengambil berita sport...
✓ Berhasil | 1757 karakter

[28/100] Mengambil berita sport...
✓ Berhasil | 1695 karakter

[29/100] Mengambil berita sport...
✓ Berhasil | 1846 karakter

[30/100] Mengambil berita sport...
✓ Berhasil | 1654 karakter

[31/100] Mengambil berita sport...
✓ Berhasil | 1561 karakter

[32/100] Mengambil berita sport...
✓ Berhasil | 1565 karakter

[33/100] Mengambil berita sport...
✓ Berhasil | 1870 karakter

[34/100] Mengambil berita sport...
✓ Berhasil | 2381 karakter

[35/100] Mengambil berita sport...
✓ Berhasil | 1380 karakter

[36/100] Mengambil berita sport...
✓ Berhasil | 1298 karakter

[37/100] Mengambil berita sport...
✓ Berhasil | 2571 karakter

[38/100] Mengambil berita sport...
✓ Berhasil | 1666 karakter

[39/100] Mengambil berita sport...
✓ Berhasil | 2386 karakter

[40/100] Mengambil berita sport...
✓ Berhasil | 1500 karakter

[41/100] Mengambil berita sport...
✓ Berhasil | 1981 karakter

[42/100] Mengambil berita sport...
✓ Berhasil | 2342 karakter

[43/100] Mengambil berita sport...
✓ Berhasil | 1683 karakter

[44/100] Mengambil berita sport...
✓ Berhasil | 3139 karakter

[45/100] Mengambil berita sport...
✓ Berhasil | 3391 karakter

[46/100] Mengambil berita sport...
✓ Berhasil | 1618 karakter

[47/100] Mengambil berita sport...
✓ Berhasil | 2907 karakter

[48/100] Mengambil berita sport...
✓ Berhasil | 1935 karakter

[49/100] Mengambil berita sport...
✓ Berhasil | 2024 karakter

[50/100] Mengambil berita sport...
✓ Berhasil | 1937 karakter

[51/100] Mengambil berita sport...
✓ Berhasil | 3022 karakter

[52/100] Mengambil berita sport...
✓ Berhasil | 1927 karakter

[53/100] Mengambil berita sport...
✓ Berhasil | 1941 karakter

[54/100] Mengambil berita sport...
✓ Berhasil | 1968 karakter

[55/100] Mengambil berita sport...
✓ Berhasil | 2221 karakter

[56/100] Mengambil berita sport...
✓ Berhasil | 3562 karakter

[57/100] Mengambil berita sport...
✓ Berhasil | 4063 karakter

[58/100] Mengambil berita sport...
✓ Berhasil | 4191 karakter

[59/100] Mengambil berita sport...
✓ Berhasil | 2390 karakter

[60/100] Mengambil berita sport...
✓ Berhasil | 1858 karakter

[61/100] Mengambil berita sport...
✓ Berhasil | 2186 karakter

[62/100] Mengambil berita sport...
✓ Berhasil | 1938 karakter

[63/100] Mengambil berita sport...
✓ Berhasil | 2305 karakter

[64/100] Mengambil berita sport...
✓ Berhasil | 4141 karakter

[65/100] Mengambil berita sport...
✓ Berhasil | 3682 karakter

[66/100] Mengambil berita sport...
✓ Berhasil | 3387 karakter

[67/100] Mengambil berita sport...
✓ Berhasil | 1589 karakter

[68/100] Mengambil berita sport...
✓ Berhasil | 2708 karakter

[69/100] Mengambil berita sport...
✓ Berhasil | 2643 karakter

[70/100] Mengambil berita sport...
✓ Berhasil | 2619 karakter

[71/100] Mengambil berita sport...
✓ Berhasil | 3005 karakter

[72/100] Mengambil berita sport...
✓ Berhasil | 2707 karakter

[73/100] Mengambil berita sport...
✓ Berhasil | 3910 karakter

[74/100] Mengambil berita sport...
✓ Berhasil | 2952 karakter

[75/100] Mengambil berita sport...
✓ Berhasil | 2217 karakter

[76/100] Mengambil berita sport...
✓ Berhasil | 2334 karakter

[77/100] Mengambil berita sport...
✓ Berhasil | 2726 karakter

[78/100] Mengambil berita sport...
✓ Berhasil | 2332 karakter

[79/100] Mengambil berita sport...
✓ Berhasil | 3087 karakter

[80/100] Mengambil berita sport...
✓ Berhasil | 159 karakter

[81/100] Mengambil berita sport...
✓ Berhasil | 2840 karakter

[82/100] Mengambil berita sport...
✓ Berhasil | 2061 karakter

[83/100] Mengambil berita sport...
✓ Berhasil | 2559 karakter

[84/100] Mengambil berita sport...
✓ Berhasil | 3004 karakter

[85/100] Mengambil berita sport...
✓ Berhasil | 1946 karakter

[86/100] Mengambil berita sport...
✓ Berhasil | 2415 karakter

[87/100] Mengambil berita sport...
✓ Berhasil | 3783 karakter

[88/100] Mengambil berita sport...
✓ Berhasil | 2205 karakter

[89/100] Mengambil berita sport...
✓ Berhasil | 3093 karakter

[90/100] Mengambil berita sport...
✓ Berhasil | 2494 karakter

[91/100] Mengambil berita sport...
✓ Berhasil | 2678 karakter

[92/100] Mengambil berita sport...
✓ Berhasil | 2101 karakter

[93/100] Mengambil berita sport...
✓ Berhasil | 5939 karakter

[94/100] Mengambil berita sport...
✓ Berhasil | 1757 karakter

[95/100] Mengambil berita sport...
✓ Berhasil | 1447 karakter

[96/100] Mengambil berita sport...
✓ Berhasil | 4511 karakter

[97/100] Mengambil berita sport...
✓ Berhasil | 2327 karakter

[98/100] Mengambil berita sport...
✓ Berhasil | 2246 karakter

[99/100] Mengambil berita sport...
✓ Berhasil | 3770 karakter

[100/100] Mengambil berita sport...
✓ Berhasil | 2114 karakter

======================================
Berita sport berhasil: 100
======================================

### 12.5 Crawling 100 Berita Finance

Setelah proses pengujian dilakukan, tahap berikutnya adalah mengambil data utama untuk kategori Finance sebanyak 100 berita. Fungsi `crawling_kategori()` digunakan kembali dengan target 100 berita, kemudian hasil crawling disimpan ke dalam variabel `data_finance`.

In [70]:
data_finance = crawling_kategori(
    finance_url,
    "finance.detik.com",
    "finance",
    100
)

======================================
CRAWLING FINANCE
Target: 100 berita
======================================

Mengambil artikel dari: https://finance.detik.com/

Mengambil halaman 1:
https://finance.detik.com/
Status: 200
  [1/100] https://finance.detik.com/moneter/d-8655958/duit-apbn-dipakai-biayai-buka-rekening-bank-purbaya-buka-suara
  [2/100] https://finance.detik.com/moneter/d-8655766/masyarakat-dibuatkan-rekening-saldo-awal-rp-50-ribu-sumber-apbn-rp-11-t
  [3/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655007/pm-singapura-sumbangkan-kenaikan-gaji-rp-24-m-selama-5-tahun
  [4/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654941/harga-emas-antam-makin-jatuh
  [5/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654769/ratusan-penerbangan-di-inggris-delay-batal-ada-apa
  [6/100] https://finance.detik.com/moneter/d-8656071/kapan-pembukaan-rekening-buat-masyarakat-dimulai-ini-jawabannya
  [7/100] https://finance.detik.com/moneter/d-8655862/bri-ditugaskan-buka-rekening-warga-ri-khusus-aceh-lewat-bsi
  [8/100] https://finance.detik.com/moneter/d-8655804/warga-usia-17-tahun-bakal-otomatis-dapat-rekening-tanpa-pergi-ke-bank
  [9/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8656057/kopdes-merah-putih-bakal-gandeng-pnm-dan-pt-pos
  [10/100] https://finance.detik.com/infrastruktur/d-8656017/otorita-ikn-minta-tambah-rp-15-8-triliun-purbaya-jawab-begini
  [11/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655884/bulog-minta-jatah-minyakita-100-mendag-tegaskan-umkm-harus-kebagian
  [12/100] https://finance.detik.com/moneter/d-8656006/bni-biayai-kopdes-merah-putih-dinilai-minim-risiko-kredit-macet
  [13/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655921/kopdes-diklaim-bikin-negara-hemat-rp-150-t-putus-mata-rantai-rentenir
  [14/100] https://finance.detik.com/foto-bisnis/d-8655963/berburu-mainan-dan-nostalgia-masa-kecil-di-kampoeng-mainan-blok-m
  [15/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655809/nasib-karyawan-telkom-yang-gedungnya-bakal-ditempati-bgn
  [16/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7390719/kisah-pilot-helikopter-banting-setir-jadi-pebisnis-teh
  [17/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7320371/panen-cuan-layanan-sayang-anabul
  [18/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7319355/menangkis-serangan-hoaks-tarik-duit-dari-bank
  [19/100] https://finance.detik.com/solusiukm/d-7309999/bisnis-kura-kura-darat-yang-bikin-dompet-gemuk
  [20/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7278891/mendulang-kasih-dan-rupiah-di-hari-raya-lewat-hampers
  [21/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7229486/ide-bisnis-lilin-aromaterapi-dari-rumah-cetak-omzet-ratusan-juta
  [22/100] https://finance.detik.com/detiktv/d-7135571/rahasia-bisnis-batik-kekinian-omzet-ratusan-juta
  [23/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7134723/rahasia-bisnis-batik-kekinian-beromzet-ratusan-juta-rupiah
  [24/100] https://finance.detik.com/berita-ekonomi-bisnis/d-7113302/belatung-pendulang-cuan-puluhan-juta-rupiah
  [25/100] https://finance.detik.com/moneter/d-8655820/warga-ri-bakal-dapat-rekening-saldo-rp-50-ribu-bisa-dicairkan
  [26/100] https://finance.detik.com/moneter/d-8655777/pemilik-ktp-baru-usia-17-tahun-otomatis-dibuatkan-rekening-bri-atau-bsi
  [27/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655808/cicilan-kopdes-merah-putih-pakai-duit-negara-purbaya-jamin-nggak-gagal-bayar
  [28/100] https://finance.detik.com/bursa-dan-valas/d-8655761/adhi-karya-buka-suara-usai-diminta-tutup-semua-anak-usaha
  [29/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655752/danantara-soal-bgn-pindah-ke-gedung-telkom-disewa-di-atas-harga-pasar
  [30/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655674/prabowo-janji-berikan-bonus-rp-3-m-buat-peraih-emas-asian-games-2026
  [31/100] https://finance.detik.com/bursa-dan-valas/d-8655589/kepala-pengawas-bursa-mineral-mau-ri-tentukan-harga-nikel-ini-alasannya
  [32/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655579/purbaya-mau-kejar-potensi-pajak-perdagangan-emas-gelap
  [33/100] https://finance.detik.com/bursa-dan-valas/d-8655574/danantara-mau-beli-saham-bei-bursa-bakal-dimiliki-pemerintah
  [34/100] https://finance.detik.com/foto-bisnis/d-8654607/bajaj-masih-eksis-di-tengah-gempuran-ojol
  [35/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655538/anak-krakatau-erupsi-harga-bahan-pokok-aman-ini-kata-mendag
  [36/100] https://finance.detik.com/industri/d-8655518/pemerintah-permudah-izin-tenaga-kerja-asing-5-hari-langsung-terbit
  [37/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655508/cuma-presentasi-online-umkm-ri-bisa-dapat-buyer-dari-33-negara
  [38/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655501/purbaya-kebut-sistem-deteksi-pajak-ekspor-impor-pakai-ai
  [39/100] https://finance.detik.com/moneter/d-8655433/punya-banyak-rencana-cek-penawaran-bri-multiguna-pre-approved
  [40/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655321/bencana-jadi-beban-ekonomi-negara
  [41/100] https://finance.detik.com/bursa-dan-valas/d-8655386/sah-sarjito-jadi-kepala-pengawas-bursa-mineral
  [42/100] https://finance.detik.com/energi/d-8655368/mglv-resmi-jadi-pemain-ai-data-center
  [43/100] https://finance.detik.com/infrastruktur/d-8655326/otorita-ikn-pastikan-karhutla-di-tol-balsam-dan-bukit-tengkorak-sudah-padam
  [44/100] https://finance.detik.com/bursa-dan-valas/d-8655301/jasa-marga-jajaki-potensi-investasi-tol-baru-siapkan-dana-rp-12-t
  [45/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655278/59-8-juta-rokok-ilegal-di-jakarta-ditindak-bea-cukai-negara-rugi-rp-46-79-m
  [46/100] https://finance.detik.com/fintech/d-8655330/bitcoin-masih-diminati-investor-ini-tandanya
  [47/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655154/bea-cukai-tindak-10-juta-batang-rokok-ilegal-yang-rugikan-negara-rp-8-m
  [48/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8645888/purbaya-siapkan-rp-40-t-bayar-utang-kopdes-ke-bank-bumn-jamin-tak-macet
  [49/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8645801/angka-kemiskinan-berbeda-dengan-versi-bank-dunia-bps-buka-suara
  [50/100] https://finance.detik.com/energi/d-8647759/pertamina-batalkan-rencana-beli-bbm-subsidi-tunjukkan-stnk
Artikel baru dari halaman ini: 50

Mengambil halaman 2:
https://finance.detik.com/indeks?page=2
Status: 200
  [51/100] https://finance.detik.com/infrastruktur/d-8655144/tol-probolinggo-banyuwangi-beroperasi-awal-2027
  [52/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655135/garuda-cek-pesawat-sebelum-terbang-lagi-imbas-abu-vulkanik
  [53/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655132/elnusa-petrofin-salurkan-bantuan-bagi-pengungsi-erupsi-gunung-sinabung
  [54/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655118/bgn-larang-susu-kental-manis-hingga-minuman-rasa-susu-di-menu-mbg
Artikel baru dari halaman ini: 4

Mengambil halaman 3:
https://finance.detik.com/indeks?page=3
Status: 200
  [55/100] https://finance.detik.com/bursa-dan-valas/d-8655085/emiten-rukun-raharja-rampungkan-akuisisi-5-saham-pt-lng
  [56/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655076/jaguar-land-rover-bakal-phk-4-000-karyawan
  [57/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655060/inggris-larang-total-impor-produk-dari-permukiman-ilegal-israel-di-tepi-barat
  [58/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655037/cuma-garuk-punggung-pria-ini-cuan-rp-220-juta-sebulan
  [59/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8655064/pengadaan-pemerintah-rp-1-200-t-bisa-jadi-peluang-buat-umkm
  [60/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654948/dari-pupuk-ke-panen-begini-peran-pupuk-indonesia-dalam-jaga-ketahanan-pangan
  [61/100] https://finance.detik.com/infrastruktur/d-8654887/otorita-ikn-buka-suara-soal-karhutla-jarak-terdekat-dengan-kipp-30-km
  [62/100] https://finance.detik.com/bursa-dan-valas/d-8654836/rupiah-tekan-dolar-as-ke-level-rp-17-500
  [63/100] https://finance.detik.com/bursa-dan-valas/d-8654828/ihsg-dibuka-balik-ke-6-700-tak-lama-lengser-ke-zona-merah
  [64/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654790/bulog-gelontorkan-beras-premium-ke-ritel-modern-di-sejumlah-kota-besar
  [65/100] https://finance.detik.com/foto-bisnis/d-8654591/cabai-rawit-merah-makin-pedas-harga-tembus-rp91-ribu
  [66/100] https://finance.detik.com/bursa-dan-valas/d-8654774/rekomendasi-saham-yang-bisa-dilirik-saat-ihsg-menguat
  [67/100] https://finance.detik.com/foto-bisnis/d-8654578/pemerintah-perkuat-database-penerima-gas-melon-lpg-3kg
  [68/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654632/puan-minta-lahan-bekas-karhutla-jadi-kebun-sawit-diusut
  [69/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654726/bps-ungkap-dtsen-bukan-daftar-penerima-bantuan-sosial
  [70/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654631/biang-kerok-sulitnya-kembalikan-aset-negara
  [71/100] https://finance.detik.com/energi/d-8654629/pertashop-terancam-tutup-ini-penyebabnya
Artikel baru dari halaman ini: 17

Mengambil halaman 4:
https://finance.detik.com/indeks?page=4
Status: 200
  [72/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654628/alasan-purbaya-kerap-omong-gede-hingga-dicap-sombong-saat-awal-jadi-menkeu
  [73/100] https://finance.detik.com/infrastruktur/d-8654625/4-fakta-utang-whoosh-dialihkan-ke-kemenkeu
  [74/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654602/masih-bingung-kelola-arus-kas-bisnis-jasamu-ikut-program-ini-solusinya
  [75/100] https://finance.detik.com/infrastruktur/d-8654568/513-9-km-listrik-aliran-atas-krl-jabodetabek-dirawat-ini-prosesnya
  [76/100] https://finance.detik.com/energi/d-8654538/sampah-kini-disulap-jadi-bensin-dan-solar
  [77/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654509/sudah-lulus-brevet-pajak-ab-saatnya-lanjut-brevet-c-untuk-cv-lebih-kuat
  [78/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654502/perusahaan-multinasional-butuh-staf-paham-pajak-lintas-negara-belajar-di-sini
  [79/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654488/purbaya-terjunkan-anak-buah-awasi-ketat-dapur-mbg
  [80/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654444/pemda-bisa-pinjam-ke-smi-bayarnya-pakai-dbh
  [81/100] https://finance.detik.com/moneter/d-8654414/purbaya-sebut-bank-ri-siap-pungut-pajak-transaksi-digital-luar-negeri
  [82/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654391/7-rekomendasi-jasa-forwarder-import-barang-dari-china-ke-indonesia
  [83/100] https://finance.detik.com/moneter/d-8654381/ungkap-pemda-punya-rp-100-triliun-nganggur-purbaya-ingatkan-tak-perlu-minjam
  [84/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654336/graha-merah-putih-akan-disewa-bgn-bos-telkom-hadirkan-peluang-bisnis-baru
  [85/100] https://finance.detik.com/moneter/d-8654356/penerima-bansos-bakal-dibuatkan-rekening-bank
  [86/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654315/telkomproperty-ungkap-pemanfaatan-graha-merah-putih-oleh-bgn-masih-negosiasi
  [87/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654240/harga-masker-mahal-imbas-abu-anak-krakatau-pengawasan-mesti-diperketat
  [88/100] https://finance.detik.com/energi/d-8654238/pertamina-waspada-solar-subsidi-bocor-selisih-harga-tembus-rp-18-200
  [89/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654233/tiktok-tokopedia-buka-suara-soal-kabar-blokir-tahan-saldo-seller
Artikel baru dari halaman ini: 18

Mengambil halaman 5:
https://finance.detik.com/indeks?page=5
Status: 200
  [90/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654222/purbaya-ngaku-tak-pusingkan-anggaran-bgn-tahun-ini-tak-sampai-rp-200-t
  [91/100] https://finance.detik.com/bursa-dan-valas/d-8654139/ihsg-ditutup-menguat-1-ke-6-686
  [92/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8654113/soal-usulan-nunggak-pajak-jadi-landasan-perampasan-aset-purbaya-bilang-gini
  [93/100] https://finance.detik.com/energi/d-8654088/bensin-campur-etanol-20-ditargetkan-jalan-2028
  [94/100] https://finance.detik.com/energi/d-8654068/terungkap-1-juta-ton-nikel-tak-bertuan-di-sulteng-bakal-dilelang
  [95/100] https://finance.detik.com/infrastruktur/d-8654044/purbaya-buka-bukaan-utang-whoosh-cicilan-rp-1-t-tenor-80-tahun
  [96/100] https://finance.detik.com/foto-bisnis/d-8653603/halim-kembali-beroperasi-mobilitas-penumpang-kembali-bergeliat
  [97/100] https://finance.detik.com/energi/d-8654009/b50-ri-bikin-jepang-malaysia-eropa-penasaran-ada-potensi-hemat-rp-170-t
  [98/100] https://finance.detik.com/berita-ekonomi-bisnis/d-8653993/bandara-soetta-sempat-ditutup-barang-ekspor-impor-rp-3-t-mandek
  [99/100] https://finance.detik.com/moneter/d-8653966/purbaya-klaim-as-tiru-ri-pindahkan-sal-ke-bank-kita-pinteran-sedikit-lah
  [100/100] https://finance.detik.com/moneter/d-8654026/jurus-bank-perkuat-likuiditas-bikin-pertumbuhan-bisnis-tetap-sehat
Artikel baru dari halaman ini: 11

======================================
Total URL finance.detik.com: 100
======================================

URL yang akan diproses: 100

[1/100] Mengambil berita finance...
✓ Berhasil | 1707 karakter

[2/100] Mengambil berita finance...
✓ Berhasil | 1468 karakter

[3/100] Mengambil berita finance...
✓ Berhasil | 2431 karakter

[4/100] Mengambil berita finance...
✓ Berhasil | 1898 karakter

[5/100] Mengambil berita finance...
✓ Berhasil | 2274 karakter

[6/100] Mengambil berita finance...
✓ Berhasil | 1489 karakter

[7/100] Mengambil berita finance...
✓ Berhasil | 1483 karakter

[8/100] Mengambil berita finance...
✓ Berhasil | 1720 karakter

[9/100] Mengambil berita finance...
✓ Berhasil | 2004 karakter

[10/100] Mengambil berita finance...
✓ Berhasil | 1653 karakter

[11/100] Mengambil berita finance...
✓ Berhasil | 2606 karakter

[12/100] Mengambil berita finance...
✓ Berhasil | 2161 karakter

[13/100] Mengambil berita finance...
✓ Berhasil | 3194 karakter

[14/100] Mengambil berita finance...
✓ Berhasil | 157 karakter

[15/100] Mengambil berita finance...
✓ Berhasil | 2943 karakter

[16/100] Mengambil berita finance...
✓ Berhasil | 1280 karakter

[17/100] Mengambil berita finance...
✓ Berhasil | 1126 karakter

[18/100] Mengambil berita finance...
✓ Berhasil | 1042 karakter

[19/100] Mengambil berita finance...
✓ Berhasil | 7013 karakter

[20/100] Mengambil berita finance...
✓ Berhasil | 1148 karakter

[21/100] Mengambil berita finance...
✓ Berhasil | 1293 karakter

[22/100] Mengambil berita finance...
✓ Berhasil | 526 karakter

[23/100] Mengambil berita finance...
✓ Berhasil | 980 karakter

[24/100] Mengambil berita finance...
✓ Berhasil | 946 karakter

[25/100] Mengambil berita finance...
✓ Berhasil | 1999 karakter

[26/100] Mengambil berita finance...
✓ Berhasil | 1392 karakter

[27/100] Mengambil berita finance...
✓ Berhasil | 2549 karakter

[28/100] Mengambil berita finance...
✓ Berhasil | 2843 karakter

[29/100] Mengambil berita finance...
✓ Berhasil | 3574 karakter

[30/100] Mengambil berita finance...
✓ Berhasil | 1512 karakter

[31/100] Mengambil berita finance...
✓ Berhasil | 3265 karakter

[32/100] Mengambil berita finance...
✓ Berhasil | 1899 karakter

[33/100] Mengambil berita finance...
✓ Berhasil | 2844 karakter

[34/100] Mengambil berita finance...
✓ Berhasil | 144 karakter

[35/100] Mengambil berita finance...
✓ Berhasil | 2001 karakter

[36/100] Mengambil berita finance...
✓ Berhasil | 2748 karakter

[37/100] Mengambil berita finance...
✓ Berhasil | 2660 karakter

[38/100] Mengambil berita finance...
✓ Berhasil | 1935 karakter

[39/100] Mengambil berita finance...
✓ Berhasil | 5502 karakter

[40/100] Mengambil berita finance...
✓ Berhasil | 3697 karakter

[41/100] Mengambil berita finance...
✓ Berhasil | 2652 karakter

[42/100] Mengambil berita finance...
✓ Berhasil | 2442 karakter

[43/100] Mengambil berita finance...
✓ Berhasil | 2351 karakter

[44/100] Mengambil berita finance...
✓ Berhasil | 2576 karakter

[45/100] Mengambil berita finance...
✓ Berhasil | 2440 karakter

[46/100] Mengambil berita finance...
✓ Berhasil | 2696 karakter

[47/100] Mengambil berita finance...
✓ Berhasil | 2604 karakter

[48/100] Mengambil berita finance...
✓ Berhasil | 1622 karakter

[49/100] Mengambil berita finance...
✓ Berhasil | 4337 karakter

[50/100] Mengambil berita finance...
✓ Berhasil | 2393 karakter

[51/100] Mengambil berita finance...
✓ Berhasil | 2446 karakter

[52/100] Mengambil berita finance...
✓ Berhasil | 4473 karakter

[53/100] Mengambil berita finance...
✓ Berhasil | 3432 karakter

[54/100] Mengambil berita finance...
✓ Berhasil | 2105 karakter

[55/100] Mengambil berita finance...
✓ Berhasil | 2966 karakter

[56/100] Mengambil berita finance...
✓ Berhasil | 2657 karakter

[57/100] Mengambil berita finance...
✓ Berhasil | 3698 karakter

[58/100] Mengambil berita finance...
✓ Berhasil | 3342 karakter

[59/100] Mengambil berita finance...
✓ Berhasil | 5940 karakter

[60/100] Mengambil berita finance...
✓ Berhasil | 8507 karakter

[61/100] Mengambil berita finance...
✓ Berhasil | 4804 karakter

[62/100] Mengambil berita finance...
✓ Berhasil | 1125 karakter

[63/100] Mengambil berita finance...
✓ Berhasil | 1207 karakter

[64/100] Mengambil berita finance...
✓ Berhasil | 3228 karakter

[65/100] Mengambil berita finance...
✓ Berhasil | 113 karakter

[66/100] Mengambil berita finance...
✓ Berhasil | 5911 karakter

[67/100] Mengambil berita finance...
✓ Berhasil | 162 karakter

[68/100] Mengambil berita finance...
✓ Berhasil | 2746 karakter

[69/100] Mengambil berita finance...
✓ Berhasil | 5158 karakter

[70/100] Mengambil berita finance...
✓ Berhasil | 3970 karakter

[71/100] Mengambil berita finance...
✓ Berhasil | 2622 karakter

[72/100] Mengambil berita finance...
✓ Berhasil | 2284 karakter

[73/100] Mengambil berita finance...
✓ Berhasil | 3049 karakter

[74/100] Mengambil berita finance...
✓ Berhasil | 1906 karakter

[75/100] Mengambil berita finance...
✓ Berhasil | 3097 karakter

[76/100] Mengambil berita finance...
✓ Berhasil | 3901 karakter

[77/100] Mengambil berita finance...
✓ Berhasil | 2089 karakter

[78/100] Mengambil berita finance...
✓ Berhasil | 2139 karakter

[79/100] Mengambil berita finance...
✓ Berhasil | 1982 karakter

[80/100] Mengambil berita finance...
✓ Berhasil | 1575 karakter

[81/100] Mengambil berita finance...
✓ Berhasil | 1684 karakter

[82/100] Mengambil berita finance...
✓ Berhasil | 6019 karakter

[83/100] Mengambil berita finance...
✓ Berhasil | 2659 karakter

[84/100] Mengambil berita finance...
✓ Berhasil | 2851 karakter

[85/100] Mengambil berita finance...
✓ Berhasil | 2214 karakter

[86/100] Mengambil berita finance...
✓ Berhasil | 2210 karakter

[87/100] Mengambil berita finance...
✓ Berhasil | 2405 karakter

[88/100] Mengambil berita finance...
✓ Berhasil | 1845 karakter

[89/100] Mengambil berita finance...
✓ Berhasil | 3391 karakter

[90/100] Mengambil berita finance...
✓ Berhasil | 2120 karakter

[91/100] Mengambil berita finance...
✓ Berhasil | 1163 karakter

[92/100] Mengambil berita finance...
✓ Berhasil | 2526 karakter

[93/100] Mengambil berita finance...
✓ Berhasil | 2591 karakter

[94/100] Mengambil berita finance...
✓ Berhasil | 2388 karakter

[95/100] Mengambil berita finance...
✓ Berhasil | 2902 karakter

[96/100] Mengambil berita finance...
✓ Berhasil | 151 karakter

[97/100] Mengambil berita finance...
✓ Berhasil | 3215 karakter

[98/100] Mengambil berita finance...
✓ Berhasil | 3600 karakter

[99/100] Mengambil berita finance...
✓ Berhasil | 2552 karakter

[100/100] Mengambil berita finance...
✓ Berhasil | 2019 karakter

======================================
Berita finance berhasil: 100
======================================

In [71]:
semua_data = (
    data_sport +
    data_finance
)

print("Total data:", len(semua_data))

Total data: 200

### 12.6 Menyimpan Dataset ke File CSV

Pada tahap ini, seluruh data berita yang sudah dikumpulkan disimpan ke dalam file CSV agar dapat digunakan pada tahap pengolahan data berikutnya. File dibuat dengan nama `dataset_berita.csv` dan memiliki tiga kolom, yaitu `id`, `isi_berita`, dan `label`.

Data pada `semua_data` kemudian ditulis satu per satu ke dalam file CSV. Nomor `id` dibuat secara berurutan mulai dari 1, sedangkan isi berita dan label diambil dari masing-masing data. Setelah proses selesai, program menampilkan pesan bahwa dataset berhasil disimpan.

In [72]:
with open(
    "dataset_berita.csv",
    "w",
    newline="",
    encoding="utf-8-sig"
) as file:

    writer = csv.writer(file)

    writer.writerow([
        "id",
        "isi_berita",
        "label"
    ])

    for i, berita in enumerate(
        semua_data,
        start=1
    ):

        writer.writerow([
            i,
            berita["isi_berita"],
            berita["label"]
        ])

print("Dataset berhasil disimpan sebagai dataset_berita.csv")

Dataset berhasil disimpan sebagai dataset_berita.csv

## 13. Membaca dan Mengecek Dataset

### 13.1 Instalasi Library Pandas

Pada tahap ini, library `pandas` diinstal untuk membantu membaca, mengolah, dan mengecek dataset yang sudah disimpan dalam format CSV.

In [ ]:
%pip install pandas

### 13.2 Membaca Dataset

Pada tahap ini, dataset hasil crawling yang telah disimpan dalam file `dataset_berita.csv` dibaca menggunakan library `pandas`. Data tersebut disimpan ke dalam variabel `df` dalam bentuk DataFrame. Setelah itu, `len(df)` digunakan untuk mengetahui jumlah seluruh data berita yang terdapat dalam dataset.

In [74]:
import pandas as pd

# Membaca dataset hasil crawling
df = pd.read_csv("dataset_berita.csv")

print("Jumlah seluruh data:", len(df))

Jumlah seluruh data: 200

### 13.3 Menampilkan Data Sport dan Finance

Pada tahap ini, ditampilkan masing-masing 5 data dari kategori Sport dan Finance untuk mengecek isi dataset yang sudah diperoleh. Data difilter berdasarkan nilai pada kolom `label`, kemudian hanya kolom `id`, `isi_berita`, dan `label` yang ditampilkan.

In [75]:
print("===== 5 DATA SPORT =====")

display(
    df[df["label"] == "sport"][
        ["id", "isi_berita", "label"]
    ].head(5)
)

print("\n===== 5 DATA FINANCE =====")

display(
    df[df["label"] == "finance"][
        ["id", "isi_berita", "label"]
    ].head(5)
)

===== 5 DATA SPORT =====

   id                                         isi_berita  label
0   1  Jakarta - Putri Kusuma Wardani percaya diri de...  sport
1   2  Jakarta - Mata Derrick Michael Xzavierro berbi...  sport
2   3  Jakarta - Marc Marquez masih harus beradaptasi...  sport
3   4  Jakarta - Momen debut di Asian Games 2026 tak ...  sport
4   5  Jakarta - MotoGP 2026 akan berlanjut ke San Ma...  sport

===== 5 DATA FINANCE =====

      id                                         isi_berita    label
100  101  Jakarta - Menteri Keuangan (Menkeu) Purbaya Yu...  finance
101  102  Jakarta - Semua masyarakat akan memiliki reken...  finance
102  103  Jakarta - Perdana Menteri (PM) Singapura, Lawr...  finance
103  104  Jakarta - Harga emas Antam terus mengalami pen...  finance
104  105  Jakarta - Penyedia kontrol lalu lintas udara, ...  finance